// AMR validation harness: 2D decaying Taylor-Green vortex, driven by the
// exact same multi-level machinery as main-amr.js/main-channel-amr.js
// (buffer layout, pipelines, S_Advance's recursive dispatch, per-level
// criterion/manage -- none of that is touched here, generated by copying
// main-channel-amr.js and swapping in the scenario-specific pieces below).
// Like the channel-flow harness, there is no body at all (HAS_BODY=0
// everywhere) and no force/torque to integrate, so amr_force*.wgsl/
// amr_physics.wgsl are never dispatched. UNLIKE channel flow, this needs
// no WALL_Y/FORCE_X wiring at all -- the domain is exactly, doubly
// periodic (see main-tgv.js's identical dense-solver rationale), which is
// also the ALREADY-VALIDATED coarse-fine interpolation path every other
// AMR page in this repo already exercises -- none of the wall-adjacent-
// interpolation gap documented in shaders/amr_interp_dense_parent.wgsl's
// header applies here, so autoRefine defaults ON (unlike
// main-channel-amr.js's deliberate default-off).
//
// This is the interesting AMR stress test the channel-flow harness isn't:
// TGV's vorticity varies smoothly but genuinely in SPACE (peak at specific
// phase points, zero at others), so real refinement patterns COULD form
// and evolve as the vortex decays -- exercising coarse-fine interpolation
// accuracy at real, moving interfaces, not just "does the machinery run."
//
// KNOWN GAP, DISCOVERED LIVE (not just theoretical), same "document +
// avoid triggering it" treatment as main-channel-amr.js's own Couette
// finding: a first attempt scaled REFINE_THRESH/COARSEN_THRESH to a
// fraction of this case's own peak vorticity (2*U0*kx at t=0), aiming for
// the "real, localized refinement pattern" described above. At this
// harness's default resolution, TGV's blockCriterion (per-block MAX
// vorticity) turned out to have a sharp cliff, not a smooth gradient, at
// the coarse (8x8-cell) block granularity -- there was no threshold
// producing a partial, localized refined region; it was either ~0 blocks
// active or ~94% of the domain (60/64) refining simultaneously. Live-
// verified: with that large-fraction-simultaneous case, L2rel-vs-analytic
// was 35x worse than the same step count with refinement OFF (3.4% vs.
// 0.097%) immediately after the first refine/coarsen cycle, and KEPT
// GROWING for over 2000 further steps with zero blocks active afterward
// (16.5%, then 19.7%) -- consistent with the coarsen/average step
// (amr_average_f2c.wgsl) leaving some real, persistent inconsistency in
// the coarse buffer when releasing a very large simultaneous batch of
// fine tiles, not a one-time interpolation-smoothing effect that would
// stay bounded. This is genuinely new territory: every other AMR
// scenario validated in this repo (cylinder wake, channel flow) only
// ever refines a SMALL localized fraction of the domain, never anywhere
// close to this scale at once. Root cause not yet isolated. Fix:
// REFINE_THRESH/COARSEN_THRESH default to main-amr.js's own fixed -6/-7
// (see below), which doesn't trigger at all for typical TGV U0/N choices
// -- `?refineThresh=-8` (etc.) opts into the demonstrated-fragile regime
// for further investigation, not for physics validation.
//
// window.__CYL exposes the same shape main-tgv.js's dense harness does
// (reset, getStep, getParams, readField) plus the AMR invariant-sweep
// surface tools/lib/amr-invariants.js needs (debugStepSync returning
// {step}, debugCheck21Balance, debugCheckGeometryCoverage -- trivially
// {ok:true}, no body to check coverage against -- debugReadCardState).

import { reportFatal, reportNoWebGPU, reportNoAdapter } from './error-overlay.mjs';
import { assembleShader } from './shader-loader.mjs';
import { packF, unpackF, fWords } from './f-pack.mjs';

const canvas   = document.getElementById('c');
const statusEl = document.getElementById('status');

const urlParams = new URLSearchParams(window.location.search);
// ?f16=1 / ?f16=2: real packed-half storage for `f` -- see shaders/common_fpack.wgsl
// and f-pack.mjs. Wired on EVERY page that consumes those shaders, including
// the ones with no accuracy check of their own: a page that quietly ignored
// ?f16= would make a green `validate-all --extra=f16=1` sweep look like it
// covered ground it never touched, which is the kind of false confidence
// this repo has been bitten by before.
const F16 = urlParams.has('f16') ? (parseInt(urlParams.get('f16')) || 0) : 0;

// ── ?ghostcopy=1 -- legacy materialized same-level ghost cells ───────────────
// Default 0: the fine step resolves a source cell that falls outside its tile
// against the owning same-level tile directly (blockSlot), so the
// between-substep fine-fine ghost COPY pass is not encoded at all. Measured
// worth 9.9% of frame GPU time on the desktop and 13.1% on the phone (the pass
// itself was 16.7-17.5%; the fine step gives 3.6-7.5% of that back, since half
// a tile's threads now pull from another slot's memory) -- see
// plans/perf-characterization.md's "The one lead left" for the full
// decomposition on both devices.
//
// 1 restores the old path exactly (clamp at the slot's own buffer edge, plus
// the copy pass), so the two can be A/B'd for both speed and physics on one
// build: `node tools/validate-all.js --extra=ghostcopy=1` runs the whole
// validation sweep against the legacy path.
const GHOST_COPY = urlParams.has('ghostcopy') ? (parseInt(urlParams.get('ghostcopy')) || 0) : 0;

// ── ?diag=1 -- refinement convergence counters ──────────────────────────────
// Makes the refine round's fixed-point loop report whether it actually
// SETTLED, instead of just running out of iterations. Off by default and
// zero-cost when off: the DIAG override gates every atomic.
const DIAG = urlParams.has('diag') ? (parseInt(urlParams.get('diag')) || 0) : 0;
// ?refineIters= overrides the fixed-point iteration count. Kept because it is
// what distinguishes an oscillation (more rounds do not help) from slow
// propagation (they do) when `converged` reads false.
const REFINE_ITERS_OVERRIDE = urlParams.has('refineIters') ? (parseInt(urlParams.get('refineIters')) || 0) : 0;

let resLog2 = parseInt(urlParams.get('res')) || 6;
// Floor of 5 (N=32, NBX=4) -- same structural minimum as main-channel-
// amr.js (more than one coarse block per axis), not the cylinder
// harness's blockage-domain-derived 7.
if (resLog2 < 5) resLog2 = 5;
if (resLog2 > 9) resLog2 = 9;

let N = 1 << resLog2;
let W = N, H = N;
let NCELLS = W * H;

let U0 = parseFloat(urlParams.get('u0')) || 0.04;
let TAU = parseFloat(urlParams.get('tau')) || 0.8;

function nuFromTau(tau) { return (tau - 0.5) / 3; }

const KX = 2 * Math.PI / N;
const KY = 2 * Math.PI / N;

function tdFromNu(nu) { return 1 / (nu * (KX * KX + KY * KY)); }

const GHOST = 2;
const BLOCK = 8;
const RB = BLOCK;
const FB = RB * 2 + 2 * GHOST;
const NCELLS1 = FB * FB;
// ── ?demandCascade=1 -- the growth half of Milestone 9's refine cascade ────
// plans/AMR-multilevel.md specifies: "a quad may only refine to level m+1 if
// its same-level neighbors are already present; if a neighbor is more than one
// level coarser, force THAT neighbor to refine first (recursively, if the gap
// is >1)". Only the veto half was ever implemented, so a criterion-driven
// refine can be vetoed forever by a neighbour that would only ever have been
// created BY that refine. Measured live on index-amr.html: level 2 never
// extends past the geometry halo into the wake, which pins the L1/L2 boundary
// a few cells off the body so every shed vortex crosses it right there.
//
// The recursion the plan asks for is a poor GPU fit, but the depth is known up
// front and the fixed-point loop below is the bounded equivalent: growth
// advances one level per iteration and the loop already runs N_LEVELS-1 times,
// which is the exact bound. See shaders/amr_manage.wgsl's level2Wanted for the
// mechanism, why it is a union with (not a replacement for) the existence-based
// cascade that superseded it, and why it stops at the L0->L1 hop.
//
// Default 0 -- provably byte-identical to the previous behaviour (level2Wanted
// is never called) until the physics is validated on the cylinder harness.
const DEMAND_CASCADE = urlParams.has('demandCascade') ? (parseInt(urlParams.get('demandCascade')) || 0) : 0;

const MAX_FINE_BLOCKS = urlParams.has('maxFineBlocks') ? parseInt(urlParams.get('maxFineBlocks')) : 128;
const NBX = W / BLOCK, NBY = H / BLOCK, NBLOCKS = NBX * NBY;

const N_LEVELS = urlParams.has('levels') ? parseInt(urlParams.get('levels')) : 2;
if (N_LEVELS < 2) throw new Error(`?levels=${N_LEVELS} invalid -- must be >= 2 (L0 + at least one fine level)`);

// Vorticity-driven refinement -- REFINE_THRESH/COARSEN_THRESH default to
// main-amr.js's own fixed -6/-7 (unchanged, NOT scaled to this case's own
// peak vorticity) -- see this file's own header for why a scaled default
// was tried and reverted. At typical U0/N choices (e.g. the default
// U0=0.04, N=64: peak vorticity 2*U0*kx=0.0079, log2~=-7.0), -6/-7 sits
// comfortably above that peak, so refinement doesn't trigger by default --
// deliberately conservative, mirroring main-channel-amr.js's own
// autoRefine-off-by-default posture, just implemented as "thresholds that
// don't fire" instead of "autoRefine off" (autoRefine itself stays ON
// here, since the machinery is safe to RUN, just not yet safe to trigger
// at TGV's own vorticity scale by default). FORCE_REFINE_MARGIN/LOOKAHEAD
// are wired through structurally (every manage pipeline expects them) but
// never gate anything: HAS_BODY=0 makes isNearBody/isNearBodyAt
// unconditionally false.
const REFINE_EVERY = urlParams.has('refineEvery') ? parseInt(urlParams.get('refineEvery')) : 16;
const REFINE_THRESH = urlParams.has('refineThresh') ? parseFloat(urlParams.get('refineThresh')) : -6;
const COARSEN_THRESH = urlParams.has('coarsenThresh') ? parseFloat(urlParams.get('coarsenThresh')) : -7;
const FORCE_REFINE_MARGIN = urlParams.has('forceRefineMargin') ? parseFloat(urlParams.get('forceRefineMargin')) : 8;
const FORCE_REFINE_LOOKAHEAD = urlParams.has('forceRefineLookahead') ? parseFloat(urlParams.get('forceRefineLookahead')) : REFINE_EVERY;

function cellSizeL0AtLevel(m) { return 2 ** -m; }

// Per-child-level REFINE_THRESH/COARSEN_THRESH/FORCE_REFINE_MARGIN/
// FORCE_REFINE_LOOKAHEAD override -- see main-channel-amr.js's identical
// function.
function paramsForChildLevel(childLevel) {
  if (childLevel === 1) {
    return { REFINE_THRESH, COARSEN_THRESH, FORCE_REFINE_MARGIN, FORCE_REFINE_LOOKAHEAD };
  }
  const get = (name, base) => urlParams.has(`${name}${childLevel}`) ? parseFloat(urlParams.get(`${name}${childLevel}`)) : base;
  return {
    REFINE_THRESH: get('refineThresh', REFINE_THRESH),
    COARSEN_THRESH: get('coarsenThresh', COARSEN_THRESH),
    FORCE_REFINE_MARGIN: get('forceRefineMargin', FORCE_REFINE_MARGIN),
    FORCE_REFINE_LOOKAHEAD: get('forceRefineLookahead', FORCE_REFINE_LOOKAHEAD),
  };
}

const resSlider = document.getElementById('slider-RES');
const resVal    = document.getElementById('val-RES');
resSlider.value = resLog2;
resVal.textContent = N;
resSlider.onchange = () => {
  const url = new URL(window.location);
  url.searchParams.set('res', resSlider.value);
  window.location.href = url.href;
};
resSlider.oninput = () => {
  resVal.textContent = 1 << parseInt(resSlider.value);
};

const u0Slider = document.getElementById('slider-U0');
const u0Val    = document.getElementById('val-U0');
u0Slider.value = U0;
u0Val.textContent = U0.toFixed(3);
u0Slider.onchange = () => {
  const url = new URL(window.location);
  url.searchParams.set('u0', u0Slider.value);
  window.location.href = url.href;
};
u0Slider.oninput = () => {
  u0Val.textContent = parseFloat(u0Slider.value).toFixed(3);
};

const EX = [0, 1, 0,-1, 0, 1,-1,-1, 1];
const EY = [0, 0, 1, 0,-1, 1, 1,-1,-1];
const WT = [4/9, 1/9, 1/9, 1/9, 1/9, 1/36, 1/36, 1/36, 1/36];
function feq(rho, ux, uy, i) {
  const eu = EX[i]*ux + EY[i]*uy;
  return WT[i] * rho * (1 + eu*3 + eu*eu*4.5 - (ux*ux+uy*uy)*1.5);
}

// Exact analytic field at t=0 -- see main-tgv.js's identical derivation.
// Indexed block-major (cellIndexJS), NOT flat row-major -- amr_step.wgsl's
// f_a/f_b buffers are laid out that way (see cellIndexJS's own comment),
// unlike main-tgv.js's dense lbm_step.wgsl, which really is flat row-major.
// Seeding at the wrong layout doesn't error (both are just NCELLS-length
// arrays) -- it silently scrambles which physical (x,y) each cell's
// analytic value lands on, corrupting the initial condition into
// something with no resemblance to the intended field.
function analyticFieldAtZero() {
  const CS2 = 1 / 3;
  const ux = new Float64Array(NCELLS), uy = new Float64Array(NCELLS), rho = new Float64Array(NCELLS);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const c = cellIndexJS(x, y);
      const cx = Math.cos(KX * x), sx = Math.sin(KX * x);
      const cy = Math.cos(KY * y), sy = Math.sin(KY * y);
      ux[c] = -U0 * cx * sy;
      uy[c] = U0 * (KX / KY) * sx * cy;
      const p = -(U0 * U0 / 4) * ((KY / KX) * Math.cos(2 * KX * x) + (KX / KY) * Math.cos(2 * KY * y));
      rho[c] = 1 + p / CS2;
    }
  }
  return { ux, uy, rho };
}

// Seed L0 at the equilibrium distribution for the exact analytic t=0
// field -- see main-tgv.js's identical rationale. Pool levels start
// entirely inactive (blockSlot=-1 everywhere) and get filled from L0 via
// the normal coarse->fine interpolation path the moment refinement first
// activates them, same as every other AMR harness here -- there's nothing
// to seed there directly, so initFPool keeps the quiescent-equilibrium
// fill (harmless: inactive slots are never read).
function initF() {
  const { ux, uy, rho } = analyticFieldAtZero();
  const f = new Float32Array(NCELLS * 9);
  for (let c = 0; c < NCELLS; c++) {
    for (let i = 0; i < 9; i++) f[i * NCELLS + c] = feq(rho[c], ux[c], uy[c], i);
  }
  return f;
}
function initFPool(maxBlocks = MAX_FINE_BLOCKS) {
  const NPOOL = maxBlocks * NCELLS1;
  const f = new Float32Array(NPOOL * 9);
  for (let c = 0; c < NPOOL; c++) {
    for (let i = 0; i < 9; i++) f[i * NPOOL + c] = feq(1, 0, 0, i);
  }
  return f;
}

// Dummy CardState: HAS_BODY=0 means every step/manage shader never lets
// these fields affect the fluid (see main-channel-amr.js's identical
// rationale).
function initCardState() {
  const card = new Float32Array(26);
  card[12] = 1; card[13] = 1; // a, b
  card[19] = TAU;
  return card;
}

async function loadShader(device, path) {
  const code = await assembleShader(path, async (p) => {
    const r = await fetch(p + '?v=' + Date.now());
    if (!r.ok) throw new Error(`failed to load ${p} (HTTP ${r.status} ${r.statusText})`);
    return r.text();
  });
  return device.createShaderModule({ code });
}

function handleErr(e) {
  // Status line AND a legible on-page overlay -- see error-overlay.mjs for why
  // the 12px status line alone was not enough.
  reportFatal(statusEl, e);
}

// Milestone 5 (plans/AMR-multilevel.md)-shaped level-generic pool
// allocation -- verbatim from main-amr.js's allocLevelPool.
function allocLevelPool(device, U, m, NBX_m, NBY_m, maxFineBlocks) {
  const NBLOCKS_m = NBX_m * NBY_m;
  const fSizePool_m = maxFineBlocks * NCELLS1 * 9 * 4;
  const pool = {
    level: m,
    NBX: NBX_m, NBY: NBY_m, NBLOCKS: NBLOCKS_m,
    MAX_FINE_BLOCKS: maxFineBlocks,
    fSizePool: fSizePool_m,
    finePoolF_a: device.createBuffer({ size: fSizePool_m, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),
    finePoolF_b: device.createBuffer({ size: fSizePool_m, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),
    // COPY_DST is load-bearing, not boilerplate: debugSnapshotLoad writes
    // this buffer via queue.writeBuffer, which is a validation error --
    // silently discarded -- without it. See velBuf's own note below.
    finePoolVel: device.createBuffer({ size: maxFineBlocks * NCELLS1 * 2 * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),
    blockSlotBuf: device.createBuffer({ size: NBLOCKS_m * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),
    slotToBlockBuf: device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),
    blockCriterionBuf: device.createBuffer({ size: NBLOCKS_m * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),  // COPY_SRC so debugReadBlockCriterion can read it back; without it the
    // copy is a validation error, the whole command buffer is dropped, and
    // the staging buffer reads back as all zeros -- which looks exactly like
    // "the criterion pass never ran" and cost a wrong diagnosis once.
    freeCountBuf: device.createBuffer({ size: 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC }),
    newlyActivatedBuf: device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST }),
  };
  if (m === 1) {
    pool.freeListBuf = device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
  } else {
    if (maxFineBlocks % 4 !== 0) {
      throw new Error(`level ${m}: MAX_FINE_BLOCKS (${maxFineBlocks}) must be a multiple of 4 (quad allocation)`);
    }
    pool.freeListBuf = device.createBuffer({ size: (maxFineBlocks / 4) * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
    const freeQuads_m = maxFineBlocks / 4;
    device.queue.writeBuffer(pool.freeListBuf, 0, new Int32Array(freeQuads_m).map((_, i) => i));
    device.queue.writeBuffer(pool.freeCountBuf, 0, new Int32Array([freeQuads_m]));
    pool.parentSlotBuf = device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
    pool.quadrantBuf   = device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
    pool.originXBuf = device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
    pool.originYBuf = device.createBuffer({ size: maxFineBlocks * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
  }
  device.queue.writeBuffer(pool.blockSlotBuf, 0, new Int32Array(NBLOCKS_m).fill(-1));
  device.queue.writeBuffer(pool.slotToBlockBuf, 0, new Int32Array(maxFineBlocks).fill(-1));
  return pool;
}

function tauAtLevel(m) {
  let t = TAU;
  for (let i = 0; i < m; i++) t = 2 * t - 0.5;
  return t;
}

// Block-major linear index for a cell at BUFFER coordinates (cx, cy) --
// matches shaders/amr_step.wgsl's cellIndex() exactly.
function cellIndexJS(cx, cy) {
  const nbx = W / BLOCK;
  const bx = Math.floor(cx / BLOCK), by = Math.floor(cy / BLOCK);
  const lx = cx % BLOCK, ly = cy % BLOCK;
  const blockID = by * nbx + bx;
  return blockID * (BLOCK * BLOCK) + ly * BLOCK + lx;
}

async function init() {
  if (!navigator.gpu) { reportNoWebGPU(statusEl); return; }
  const adapter = await navigator.gpu.requestAdapter();
  if (!adapter) { reportNoAdapter(statusEl); return; }

  const DEFAULT_MAX_STORAGE_BINDING = 128 * 1024 * 1024;
  const DEFAULT_MAX_BUFFER_SIZE = 256 * 1024 * 1024;
  const neededBufferBytes = NCELLS * 9 * 4;
  if (neededBufferBytes > adapter.limits.maxStorageBufferBindingSize) {
    const mib = (b) => (b / 1048576).toFixed(0);
    statusEl.textContent = `error: ${W}x${H} needs a ${mib(neededBufferBytes)} MiB buffer binding, this GPU's max is ${mib(adapter.limits.maxStorageBufferBindingSize)} MiB`;
    return;
  }
  const NEEDED_STORAGE_BUFFERS_PER_STAGE = 16;
  if (NEEDED_STORAGE_BUFFERS_PER_STAGE > adapter.limits.maxStorageBuffersPerShaderStage) {
    statusEl.textContent = `error: needs ${NEEDED_STORAGE_BUFFERS_PER_STAGE} storage buffers per shader stage, this GPU's max is ${adapter.limits.maxStorageBuffersPerShaderStage}`;
    return;
  }
  const requiredLimits = {
    maxStorageBufferBindingSize: Math.min(Math.max(neededBufferBytes, DEFAULT_MAX_STORAGE_BINDING), adapter.limits.maxStorageBufferBindingSize),
    maxBufferSize: Math.min(Math.max(neededBufferBytes, DEFAULT_MAX_BUFFER_SIZE), adapter.limits.maxBufferSize),
    maxStorageBuffersPerShaderStage: NEEDED_STORAGE_BUFFERS_PER_STAGE,
  };
  const device = await adapter.requestDevice({ requiredLimits });

  device.pushErrorScope('validation');

  const ctx = canvas.getContext('webgpu');
  const fmt = navigator.gpu.getPreferredCanvasFormat();

  // Reconfigure ONLY on a real size change. This used to run unconditionally
  // on every `resize` event, and both halves of it are destructive:
  // assigning canvas.width/height resets the drawing buffer even when the
  // value is unchanged, and ctx.configure() replaces the swapchain,
  // invalidating textures that in-flight command buffers still reference
  // (this page keeps up to STAGES frames in flight).
  //
  // On desktop `resize` fires when you resize the window, so the cost was
  // invisible. On a PHONE it fires constantly -- the URL bar hides and shows
  // on any scroll or drag, which includes touching the control sliders --
  // so the swapchain was being torn down and rebuilt underneath frames that
  // were already submitted. Reported symptom: the view "twitches back" a few
  // frames, correlated with moving sliders or switching away and back.
  //
  // Also guards the degenerate case: clientWidth/Height read 0 during some
  // layout transitions (and while hidden), and a 0-sized canvas is not a
  // valid configuration.
  let cfgW = 0, cfgH = 0;
  function resize() {
    const dpr = window.devicePixelRatio || 1;
    const w = Math.round(canvas.clientWidth * dpr);
    const h = Math.round(canvas.clientHeight * dpr);
    if (w <= 0 || h <= 0) return;      // mid-layout / hidden: nothing to configure
    if (w === cfgW && h === cfgH) return; // same size: reconfiguring is pure damage
    cfgW = w; cfgH = h;
    canvas.width = w;
    canvas.height = h;
    ctx.configure({ device, format: fmt, alphaMode: 'opaque' });
  }
  window.addEventListener('resize', resize);
  resize();

  const U = GPUBufferUsage;
  const fSize   = NCELLS * 9 * 4;
  const f_a     = device.createBuffer({ size: fSize, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
  const f_b     = device.createBuffer({ size: fSize, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
  // COPY_DST: debugSnapshotLoad restores this with queue.writeBuffer.
  // Without the flag that write is a validation error and is silently
  // dropped, so a loaded snapshot keeps whatever ux/uy were already there.
  // The load path's own comment already describes this exact symptom
  // ("rho round-tripped exactly, but ux/uy didn't -- the asymmetry was the
  // tell") -- the writeBuffer call was added then, but the usage flag was
  // not, so the fix never actually took effect.
  const velBuf  = device.createBuffer({ size: NCELLS * 2 * 4, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });
  // ?diag=1 counters -- 8 u32 slots, read+zeroed via debugReadDiag().
  const diagBuf = device.createBuffer({ size: 8 * 4, usage: U.STORAGE | U.COPY_SRC | U.COPY_DST });
  const diagReadBuf = device.createBuffer({ size: 8 * 4, usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ });
  const dummyBlockSlotBuf = device.createBuffer({ size: 4, usage: U.STORAGE | U.COPY_DST });
  device.queue.writeBuffer(dummyBlockSlotBuf, 0, new Int32Array([-1]));
  const dummyCriterionBuf = device.createBuffer({ size: 4, usage: U.STORAGE | U.COPY_DST });
  device.queue.writeBuffer(dummyCriterionBuf, 0, new Float32Array([0]));

  // See main-amr.js's copy for the rationale: the GPU buffer holds packed
  // half pairs under F16, everything else speaks f32 plane-major, and these
  // two are the only places the two meet.
  const writeF = (buf, f32, ncells) => {
    const src = packF(f32, ncells, F16);
    device.queue.writeBuffer(buf, 0, src.buffer, src.byteOffset, ncells * fWords(F16) * 4);
  };
  const readF = (mapped, ncells) =>
    F16 ? unpackF(new Uint32Array(mapped), ncells, true) : new Float32Array(mapped).slice();

  const cardStateBuf = device.createBuffer({ size: 104, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });

  const pools = [undefined];
  {
    let curNBX = NBX, curNBY = NBY;
    for (let m = 1; m < N_LEVELS; m++) {
      const maxFineBlocks = m === 1
        ? MAX_FINE_BLOCKS
        : (urlParams.has(`maxFineBlocks${m}`) ? parseInt(urlParams.get(`maxFineBlocks${m}`)) : 128);
      const pool = allocLevelPool(device, U, m, curNBX, curNBY, maxFineBlocks);
      writeF(pool.finePoolF_a, initFPool(maxFineBlocks), maxFineBlocks * NCELLS1);
      pools.push(pool);
      curNBX *= 2; curNBY *= 2;
    }
  }

  device.queue.writeBuffer(cardStateBuf, 0, initCardState());
  writeF(f_a, initF(), NCELLS);
  device.queue.writeBuffer(pools[1].freeListBuf, 0, new Int32Array(MAX_FINE_BLOCKS).map((_, i) => i));
  device.queue.writeBuffer(pools[1].freeCountBuf, 0, new Int32Array([MAX_FINE_BLOCKS]));

  for (let c = 2; c < N_LEVELS; c++) {
    const pool = pools[c];
    pool.levelParamsBuf = device.createBuffer({ size: 32, usage: U.UNIFORM | U.COPY_DST });
    const staticBuf = new ArrayBuffer(32);
    const staticDv = new DataView(staticBuf);
    staticDv.setUint32(0, pool.NBX, true);
    staticDv.setUint32(4, pool.NBY, true);
    staticDv.setFloat32(12, cellSizeL0AtLevel(c), true);
    staticDv.setUint32(16, (c + 1) < N_LEVELS ? 1 : 0, true);
    device.queue.writeBuffer(pool.levelParamsBuf, 0, staticBuf);
  }
  function updateLevelParams() {
    for (let c = 2; c < N_LEVELS; c++) {
      device.queue.writeBuffer(pools[c].levelParamsBuf, 8, new Float32Array([tauAtLevel(c - 1)]));
    }
  }
  updateLevelParams();

  const overlaySlider = document.getElementById('slider-overlay');
  const overlayValEl = document.getElementById('val-overlay');

  const [stepSM, renSM, interpDenseSM, interpPoolSM, step1SM, step1PoolSM, avgSM, avgPoolSM, criterionSM, manageSM, criterionPoolSM, managePoolSM] = await Promise.all([
    loadShader(device, 'shaders/amr_step.wgsl'),
    loadShader(device, 'shaders/amr_render.wgsl'),
    loadShader(device, 'shaders/amr_interp_dense_parent.wgsl'),
    loadShader(device, 'shaders/amr_interp_pool_parent.wgsl'),
    loadShader(device, 'shaders/amr_step1.wgsl'),
    loadShader(device, 'shaders/amr_step1_pool.wgsl'),
    loadShader(device, 'shaders/amr_average_f2c.wgsl'),
    loadShader(device, 'shaders/amr_average_pool_parent.wgsl'),
    loadShader(device, 'shaders/amr_criterion.wgsl'),
    loadShader(device, 'shaders/amr_manage.wgsl'),
    loadShader(device, 'shaders/amr_criterion_pool.wgsl'),
    loadShader(device, 'shaders/amr_manage_pool.wgsl'),
  ]);

  const stepBGL = device.createBindGroupLayout({ label: 'stepBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } }
  ]});
  const renBGL = device.createBindGroupLayout({ label: 'renBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'read-only-storage' } },
    { binding: 3, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'read-only-storage' } },
    { binding: 4, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'uniform' } },
    { binding: 5, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'read-only-storage' } },
    { binding: 6, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'read-only-storage' } },
    { binding: 7, visibility: GPUShaderStage.FRAGMENT, buffer: { type: 'uniform' } }
  ]});
  const interpBGL = device.createBindGroupLayout({ label: 'interpBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 4, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 5, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } }
  ]});
  const interpPoolParentBGL = device.createBindGroupLayout({ label: 'interpPoolParentBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'uniform' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 4, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 5, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 6, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 7, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } }
  ]});
  const criterionBGL = device.createBindGroupLayout({ label: 'criterionBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } }
  ]});
  const manageBGL = device.createBindGroupLayout({ label: 'manageBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 4, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 5, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 6, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 7, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 8, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    // binding 9: ?diag=1 convergence counters. Always bound; never touched at DIAG=0.
    { binding: 9, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } }
  ]});
  const criterionPoolBGL = device.createBindGroupLayout({ label: 'criterionPoolBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } }
  ]});
  const managePoolBGL = device.createBindGroupLayout({ label: 'managePoolBGL', entries: [
    { binding: 0,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 2,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 4,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 5,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 6,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 7,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 8,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 9,  visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 10, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 11, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 12, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 13, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 14, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 15, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
  ]});
  const step1BGL = device.createBindGroupLayout({ label: 'step1BGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 4, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    // binding 5: blockSlot -- neighbour-addressed streaming (see the
    // DIRECT_GHOST override in shaders/amr_step1.wgsl). Present in the layout
    // even under ?ghostcopy=1, where the shader simply never reads it.
    { binding: 5, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } }
  ]});
  const avgBGL = device.createBindGroupLayout({ label: 'avgBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } }
  ]});
  const step1PoolBGL = device.createBindGroupLayout({ label: 'step1PoolBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 4, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 5, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 6, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 7, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'uniform' } },
    // binding 8: blockSlot -- see step1BGL's binding 5.
    { binding: 8, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } }
  ]});
  const avgPoolBGL = device.createBindGroupLayout({ label: 'avgPoolBGL', entries: [
    { binding: 0, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'uniform' } },
    { binding: 1, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 2, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'storage' } },
    { binding: 3, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 4, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } },
    { binding: 5, visibility: GPUShaderStage.COMPUTE, buffer: { type: 'read-only-storage' } }
  ]});

  const constants = { W, H };

  // Fully periodic, no body, no walls, no force -- see this file's header.
  const stepConstants = { W, H, HAS_BODY: 0, SPONGE_W: 0, F16 };
  const fineConstants = { W, H, RB };
  // Split from fineConstants, which also drives the render fragment --
  // render.wgsl has no F16 override and WebGPU rejects an undeclared one.
  const avgConstants = { W, H, RB, F16 };

  const interpConstants = { W, H, RB, GHOST_ONLY: 1, F16 };
  const interpInitConstants = { W, H, RB, GHOST_ONLY: 0, F16 };
  const interpFFConstants = { W, H, RB, GHOST_ONLY: 1, FINE_FINE_ONLY: 1, F16 };
  const step1Constants = { ...stepConstants, RB, DIRECT_GHOST: GHOST_COPY ? 0 : 1 };
  const criterionConstants = { W, H };
  const manageConstants = { DIAG, W, H, REFINE_THRESH, COARSEN_THRESH, FORCE_REFINE_MARGIN, FORCE_REFINE_LOOKAHEAD, DEMAND_CASCADE, HAS_LEVEL2: N_LEVELS > 2 ? 1 : 0, HAS_BODY: 0 };

  const stepPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [stepBGL] }),
    compute: { module: stepSM, entryPoint: 'main', constants: stepConstants }
  });
  const step1PL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [step1BGL] }),
    compute: { module: step1SM, entryPoint: 'main', constants: step1Constants }
  });
  const step1PoolPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [step1PoolBGL] }),
    compute: { module: step1PoolSM, entryPoint: 'main', constants: { ...step1Constants, K_EPS: 1.5, F16 } }
  });

  const renPL = device.createRenderPipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [renBGL] }),
    vertex: { module: renSM, entryPoint: 'vs_main', constants },
    fragment: { module: renSM, entryPoint: 'fs_main', targets: [{ format: fmt }], constants: fineConstants },
    primitive: { topology: 'triangle-list' },
  });
  const interpPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [interpBGL] }),
    compute: { module: interpDenseSM, entryPoint: 'main', constants: interpConstants }
  });
  const interpInitPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [interpBGL] }),
    compute: { module: interpDenseSM, entryPoint: 'main', constants: interpInitConstants }
  });
  const interpFFPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [interpBGL] }),
    compute: { module: interpDenseSM, entryPoint: 'main', constants: interpFFConstants }
  });
  const interpPoolConstants = { RB, GHOST_ONLY: 1, F16 };
  const interpPoolInitConstants = { RB, GHOST_ONLY: 0, F16 };
  const interpPoolFFConstants = { RB, GHOST_ONLY: 1, FINE_FINE_ONLY: 1, F16 };
  const interpPoolParentPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [interpPoolParentBGL] }),
    compute: { module: interpPoolSM, entryPoint: 'main', constants: interpPoolConstants }
  });
  const interpPoolParentInitPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [interpPoolParentBGL] }),
    compute: { module: interpPoolSM, entryPoint: 'main', constants: interpPoolInitConstants }
  });
  const interpPoolParentFFPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [interpPoolParentBGL] }),
    compute: { module: interpPoolSM, entryPoint: 'main', constants: interpPoolFFConstants }
  });
  const avgPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [avgBGL] }),
    compute: { module: avgSM, entryPoint: 'main', constants: avgConstants }
  });
  const avgPoolPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [avgPoolBGL] }),
    compute: { module: avgPoolSM, entryPoint: 'main', constants: { RB, F16 } }
  });
  const criterionPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [criterionBGL] }),
    compute: { module: criterionSM, entryPoint: 'main', constants: criterionConstants }
  });
  const manageCoarsenPL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [manageBGL] }),
    compute: { module: manageSM, entryPoint: 'coarsen', constants: manageConstants }
  });
  const manageRefinePL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [manageBGL] }),
    compute: { module: manageSM, entryPoint: 'refine', constants: manageConstants }
  });

  const criterionPoolPLs = {};
  const managePoolCoarsenPLs = {};
  const managePoolRefinePLs = {};
  for (let m = 1; m < N_LEVELS - 1; m++) {
    const parentPool = pools[m];
    const parentIsDense = m === 1;
    const childParams = paramsForChildLevel(m + 1);
    const hasGrandchild = (m + 2) < N_LEVELS;
    const poolConstants = {
      W, H, RB,
      NBX_PARENT: parentPool.NBX, NBY_PARENT: parentPool.NBY,
      PARENT_CELL_SIZE_L0: cellSizeL0AtLevel(m),
      PARENT_HAS_CACHED_ORIGIN: parentIsDense ? 0 : 1,
      ...childParams,
      HAS_GRANDCHILD: hasGrandchild ? 1 : 0,
      HAS_BODY: 0,
    };
    criterionPoolPLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [criterionPoolBGL] }),
      compute: { module: criterionPoolSM, entryPoint: 'main', constants: { RB, NBX_PARENT: parentPool.NBX } }
    });
    managePoolCoarsenPLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [managePoolBGL] }),
      compute: { module: managePoolSM, entryPoint: 'coarsen', constants: poolConstants }
    });
    managePoolRefinePLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [managePoolBGL] }),
      compute: { module: managePoolSM, entryPoint: 'refine', constants: poolConstants }
    });
  }

  const stepBG_ab = device.createBindGroup({ layout: stepBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_a } }, { binding: 2, resource: { buffer: f_b } }, { binding: 3, resource: { buffer: velBuf } }]});
  const stepBG_ba = device.createBindGroup({ layout: stepBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_b } }, { binding: 2, resource: { buffer: f_a } }, { binding: 3, resource: { buffer: velBuf } }]});
  const step1BG_ab = device.createBindGroup({ layout: step1BGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: pools[1].finePoolF_a } }, { binding: 2, resource: { buffer: pools[1].finePoolF_b } }, { binding: 3, resource: { buffer: pools[1].finePoolVel } }, { binding: 4, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});
  const step1BG_ba = device.createBindGroup({ layout: step1BGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: pools[1].finePoolF_b } }, { binding: 2, resource: { buffer: pools[1].finePoolF_a } }, { binding: 3, resource: { buffer: pools[1].finePoolVel } }, { binding: 4, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});

  const overlayOpacityBuf = device.createBuffer({ size: 4, usage: U.UNIFORM | U.COPY_DST });
  device.queue.writeBuffer(overlayOpacityBuf, 0, new Float32Array([1.0]));
  const outlineOpacityBuf = device.createBuffer({ size: 4, usage: U.UNIFORM | U.COPY_DST });
  device.queue.writeBuffer(outlineOpacityBuf, 0, new Float32Array([0.0]));
  if (overlaySlider) {
    overlaySlider.oninput = () => {
      const v = parseFloat(overlaySlider.value);
      overlayValEl.textContent = v.toFixed(2);
      device.queue.writeBuffer(overlayOpacityBuf, 0, new Float32Array([v]));
    };
  }
  const renBG = device.createBindGroup({ layout: renBGL, entries: [{ binding: 0, resource: { buffer: velBuf } }, { binding: 1, resource: { buffer: cardStateBuf } }, { binding: 2, resource: { buffer: pools[1].finePoolVel } }, { binding: 3, resource: { buffer: pools[1].blockSlotBuf } }, { binding: 4, resource: { buffer: overlayOpacityBuf } }, { binding: 5, resource: { buffer: N_LEVELS > 2 ? pools[2].finePoolVel : pools[1].finePoolVel } }, { binding: 6, resource: { buffer: N_LEVELS > 2 ? pools[2].blockSlotBuf : dummyBlockSlotBuf } }, { binding: 7, resource: { buffer: outlineOpacityBuf } }]});

  const interpBG_readA = device.createBindGroup({ layout: interpBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_a } }, { binding: 2, resource: { buffer: pools[1].finePoolF_a } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 4, resource: { buffer: pools[1].newlyActivatedBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});
  const interpBG_readB = device.createBindGroup({ layout: interpBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_b } }, { binding: 2, resource: { buffer: pools[1].finePoolF_a } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 4, resource: { buffer: pools[1].newlyActivatedBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});
  const interpFFBG_b = device.createBindGroup({ layout: interpBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_a } }, { binding: 2, resource: { buffer: pools[1].finePoolF_b } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 4, resource: { buffer: pools[1].newlyActivatedBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});
  const avgBG_targetA = device.createBindGroup({ layout: avgBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: pools[1].finePoolF_a } }, { binding: 2, resource: { buffer: f_a } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }]});
  const avgBG_targetB = device.createBindGroup({ layout: avgBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: pools[1].finePoolF_a } }, { binding: 2, resource: { buffer: f_b } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }]});
  const interpInitBG_readA = device.createBindGroup({ layout: interpBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_a } }, { binding: 2, resource: { buffer: pools[1].finePoolF_a } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 4, resource: { buffer: pools[1].newlyActivatedBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});
  const interpInitBG_readB = device.createBindGroup({ layout: interpBGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: f_b } }, { binding: 2, resource: { buffer: pools[1].finePoolF_a } }, { binding: 3, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 4, resource: { buffer: pools[1].newlyActivatedBuf } }, { binding: 5, resource: { buffer: pools[1].blockSlotBuf } }]});

  const criterionBG = device.createBindGroup({ layout: criterionBGL, entries: [{ binding: 0, resource: { buffer: velBuf } }, { binding: 1, resource: { buffer: pools[1].blockCriterionBuf } }]});
  const manageBG = device.createBindGroup({ layout: manageBGL, entries: [{ binding: 0, resource: { buffer: pools[1].blockCriterionBuf } }, { binding: 1, resource: { buffer: pools[1].blockSlotBuf } }, { binding: 2, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 3, resource: { buffer: pools[1].freeListBuf } }, { binding: 4, resource: { buffer: pools[1].freeCountBuf } }, { binding: 5, resource: { buffer: pools[1].newlyActivatedBuf } }, { binding: 6, resource: { buffer: cardStateBuf } }, { binding: 7, resource: { buffer: N_LEVELS > 2 ? pools[2].blockCriterionBuf : dummyCriterionBuf } }, { binding: 8, resource: { buffer: N_LEVELS > 2 ? pools[2].blockSlotBuf : dummyBlockSlotBuf } }, { binding: 9, resource: { buffer: diagBuf } }]});

  const criterionPoolBGs = {};
  const managePoolBGs = {};
  for (let m = 1; m < N_LEVELS - 1; m++) {
    const parentPool = pools[m];
    const childPool = pools[m + 1];
    // BUGFIX: ALWAYS the parent pool's own finePoolVel, never velBuf.
    // amr_criterion_pool.wgsl's binding 0 is the PARENT LEVEL's fine pool
    // velocity and it addresses that buffer BY POOL SLOT
    // (slot*(FB*FB) + fy*FB + fx). This shader only ever runs with a pool
    // level as its parent -- m >= 1 -- so there is no dense case to special-
    // case here; the `m === 1 ? velBuf : ...` this replaces was the
    // dense-parent pattern the neighbouring interp/step bind groups legitimately
    // use, copied to a shader that has no dense-parent variant.
    //
    // Handing it velBuf fed a dense, cellIndex-addressed L0 buffer to
    // slot-addressed reads: wrong layout for every slot, and past roughly the
    // first third of the slots the reads run off the end of a buffer less than
    // half the size the pool layout expects. The result was a level-2
    // blockCriterion of essentially ZERO everywhere -- measured 2^-39.86 for
    // all 85 active L1 parents, against a host reconstruction from level 1's
    // own field showing up to 2^-5.6.
    //
    // So amr_manage_pool.wgsl's refine() saw maxCrit ~= 0 for every parent,
    // desiredLevel(toPhysical(eps)) was 0, and the vorticity criterion could
    // NEVER promote a tile to level 2. Level 2 was 100% geometry-forced --
    // which is exactly what a phi scan showed independently before the cause
    // was known: L2 covered block centres at phi -0.5 .. 7.9, the
    // childLevel-2 forced halo (margin 8) and nothing beyond it. That pins
    // the L1/L2 boundary a few cells off the body, so every shed vortex
    // crosses it right at the trailing edge -- the reported block artifacts
    // and the lumpiness induced on the shed vortices.
    const parentVel = parentPool.finePoolVel;
    const parentSlotToBlockBuf = m === 1 ? pools[1].slotToBlockBuf : parentPool.slotToBlockBuf;
    const parentBlockSlotBuf = m === 1 ? pools[1].blockSlotBuf : parentPool.blockSlotBuf;
    const parentOriginXBuf = m === 1 ? dummyBlockSlotBuf : parentPool.originXBuf;
    const parentOriginYBuf = m === 1 ? dummyBlockSlotBuf : parentPool.originYBuf;
    const grandchildPool = (m + 2) < N_LEVELS ? pools[m + 2] : null;
    const grandchildBlockSlotBuf = grandchildPool ? grandchildPool.blockSlotBuf : dummyBlockSlotBuf;

    criterionPoolBGs[m] = device.createBindGroup({ layout: criterionPoolBGL, entries: [
      { binding: 0, resource: { buffer: parentVel } },
      { binding: 1, resource: { buffer: parentSlotToBlockBuf } },
      { binding: 2, resource: { buffer: childPool.blockCriterionBuf } },
    ]});
    managePoolBGs[m] = device.createBindGroup({ layout: managePoolBGL, entries: [
      { binding: 0, resource: { buffer: childPool.blockCriterionBuf } },
      { binding: 1, resource: { buffer: childPool.blockSlotBuf } },
      { binding: 2, resource: { buffer: childPool.slotToBlockBuf } },
      { binding: 3, resource: { buffer: childPool.freeListBuf } },
      { binding: 4, resource: { buffer: childPool.freeCountBuf } },
      { binding: 5, resource: { buffer: childPool.newlyActivatedBuf } },
      { binding: 6, resource: { buffer: cardStateBuf } },
      { binding: 7, resource: { buffer: childPool.parentSlotBuf } },
      { binding: 8, resource: { buffer: childPool.quadrantBuf } },
      { binding: 9, resource: { buffer: childPool.originXBuf } },
      { binding: 10, resource: { buffer: childPool.originYBuf } },
      { binding: 11, resource: { buffer: parentBlockSlotBuf } },
      { binding: 12, resource: { buffer: parentSlotToBlockBuf } },
      { binding: 13, resource: { buffer: parentOriginXBuf } },
      { binding: 14, resource: { buffer: parentOriginYBuf } },
      { binding: 15, resource: { buffer: grandchildBlockSlotBuf } },
    ]});
  }

  for (let c = 2; c < N_LEVELS; c++) {
    const parentPool = pools[c - 1];
    const childPool = pools[c];
    const interpEntries = (parentBuf) => [
      { binding: 0, resource: { buffer: childPool.levelParamsBuf } },
      { binding: 1, resource: { buffer: parentBuf } },
      { binding: 2, resource: { buffer: childPool.finePoolF_a } },
      { binding: 3, resource: { buffer: childPool.slotToBlockBuf } },
      { binding: 4, resource: { buffer: childPool.newlyActivatedBuf } },
      { binding: 5, resource: { buffer: childPool.blockSlotBuf } },
      { binding: 6, resource: { buffer: childPool.parentSlotBuf } },
      { binding: 7, resource: { buffer: childPool.quadrantBuf } },
    ];
    childPool.interpPoolParentBG_readA = device.createBindGroup({ layout: interpPoolParentBGL, entries: interpEntries(parentPool.finePoolF_a) });
    childPool.interpPoolParentBG_readB = device.createBindGroup({ layout: interpPoolParentBGL, entries: interpEntries(parentPool.finePoolF_b) });
    childPool.interpPoolParentFFBG_b = device.createBindGroup({ layout: interpPoolParentBGL, entries: interpEntries(parentPool.finePoolF_a).map((e, i) => i === 2 ? { binding: 2, resource: { buffer: childPool.finePoolF_b } } : e) });

    childPool.step1PoolBG_ab = device.createBindGroup({ layout: step1PoolBGL, entries: [
      { binding: 0, resource: { buffer: cardStateBuf } },
      { binding: 1, resource: { buffer: childPool.finePoolF_a } },
      { binding: 2, resource: { buffer: childPool.finePoolF_b } },
      { binding: 3, resource: { buffer: childPool.finePoolVel } },
      { binding: 4, resource: { buffer: childPool.slotToBlockBuf } },
      { binding: 5, resource: { buffer: childPool.originXBuf } },
      { binding: 6, resource: { buffer: childPool.originYBuf } },
      { binding: 7, resource: { buffer: childPool.levelParamsBuf } },
      { binding: 8, resource: { buffer: childPool.blockSlotBuf } },
    ]});
    childPool.step1PoolBG_ba = device.createBindGroup({ layout: step1PoolBGL, entries: [
      { binding: 0, resource: { buffer: cardStateBuf } },
      { binding: 1, resource: { buffer: childPool.finePoolF_b } },
      { binding: 2, resource: { buffer: childPool.finePoolF_a } },
      { binding: 3, resource: { buffer: childPool.finePoolVel } },
      { binding: 4, resource: { buffer: childPool.slotToBlockBuf } },
      { binding: 5, resource: { buffer: childPool.originXBuf } },
      { binding: 6, resource: { buffer: childPool.originYBuf } },
      { binding: 7, resource: { buffer: childPool.levelParamsBuf } },
      { binding: 8, resource: { buffer: childPool.blockSlotBuf } },
    ]});

    const avgEntries = (parentBuf) => [
      { binding: 0, resource: { buffer: childPool.levelParamsBuf } },
      { binding: 1, resource: { buffer: childPool.finePoolF_a } },
      { binding: 2, resource: { buffer: parentBuf } },
      { binding: 3, resource: { buffer: childPool.slotToBlockBuf } },
      { binding: 4, resource: { buffer: childPool.parentSlotBuf } },
      { binding: 5, resource: { buffer: childPool.quadrantBuf } },
    ];
    childPool.avgPoolBG_targetA = device.createBindGroup({ layout: avgPoolBGL, entries: avgEntries(parentPool.finePoolF_a) });
    childPool.avgPoolBG_targetB = device.createBindGroup({ layout: avgPoolBGL, entries: avgEntries(parentPool.finePoolF_b) });
  }

  const error = await device.popErrorScope();
  if (error) { handleErr(error); return; }

  const WGX = Math.ceil(W / 8), WGY = Math.ceil(H / 8);
  const WGX1 = Math.ceil(FB / 8), WGY1 = Math.ceil(FB / 8);
  const WG_MANAGE = Math.ceil(NBLOCKS / 64);
  const STEPS_PER_FRAME = 64;
  let step = 0, lastT = performance.now();
  let useB = false;
  let liveMode = true;
  // Default ON, unlike main-channel-amr.js -- see this file's own header:
  // TGV is fully periodic with no interior body, exactly the ALREADY-
  // VALIDATED coarse-fine interpolation path every other AMR page here
  // already exercises, so there's no known corruption risk the way
  // channel flow's real walls created for Couette.
  let autoRefine = urlParams.get('autoRefine') !== '0';
  let macroStepCounter = 0;

  // ── Recursive multi-level advance -- byte-for-byte identical dispatch
  // sequence to main-amr.js's own S_Advance, with force/torque integration
  // removed (no body here) -- see main-channel-amr.js's identical copy.
  function S_Advance(level, enc) {
    const hasChild = (level + 1) < N_LEVELS;

    if (level === 0) {
      const stepBG = useB ? stepBG_ba : stepBG_ab;
      if (hasChild) {
        const readBG = useB ? interpBG_readB : interpBG_readA;
        const p = enc.beginComputePass(); p.setPipeline(interpPL); p.setBindGroup(0, readBG); p.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); p.end();
      }
      const s = enc.beginComputePass(); s.setPipeline(stepPL); s.setBindGroup(0, stepBG); s.dispatchWorkgroups(WGX, WGY); s.end();
      if (hasChild) {
        S_Advance(1, enc);
        const avgBG = useB ? avgBG_targetA : avgBG_targetB;
        const a = enc.beginComputePass(); a.setPipeline(avgPL); a.setBindGroup(0, avgBG); a.dispatchWorkgroups(1, 1, MAX_FINE_BLOCKS); a.end();
      }
      return;
    }

    const pool = pools[level];
    const isL1 = level === 1;
    let cur = 'a';

    const interpIntoChild = (readCur) => {
      if (!hasChild) return;
      const childPool = pools[level + 1];
      const bg = readCur === 'a' ? childPool.interpPoolParentBG_readA : childPool.interpPoolParentBG_readB;
      const p = enc.beginComputePass(); p.setPipeline(interpPoolParentPL); p.setBindGroup(0, bg); p.dispatchWorkgroups(WGX1, WGY1, childPool.MAX_FINE_BLOCKS); p.end();
    };
    const averageFromChild = (writeCur) => {
      if (!hasChild) return;
      const childPool = pools[level + 1];
      const bg = writeCur === 'a' ? childPool.avgPoolBG_targetA : childPool.avgPoolBG_targetB;
      const p = enc.beginComputePass(); p.setPipeline(avgPoolPL); p.setBindGroup(0, bg); p.dispatchWorkgroups(1, 1, childPool.MAX_FINE_BLOCKS); p.end();
    };
    const substep = (readCur) => {
      if (isL1) {
        const bg = readCur === 'a' ? step1BG_ab : step1BG_ba;
        const p = enc.beginComputePass(); p.setPipeline(step1PL); p.setBindGroup(0, bg); p.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); p.end();
      } else {
        const bg = readCur === 'a' ? pool.step1PoolBG_ab : pool.step1PoolBG_ba;
        const p = enc.beginComputePass(); p.setPipeline(step1PoolPL); p.setBindGroup(0, bg); p.dispatchWorkgroups(WGX1, WGY1, pool.MAX_FINE_BLOCKS); p.end();
      }
    };
    const fineFineRefresh = () => {
      if (isL1) {
        const p = enc.beginComputePass(); p.setPipeline(interpFFPL); p.setBindGroup(0, interpFFBG_b); p.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); p.end();
      } else {
        const p = enc.beginComputePass(); p.setPipeline(interpPoolParentFFPL); p.setBindGroup(0, pool.interpPoolParentFFBG_b); p.dispatchWorkgroups(WGX1, WGY1, pool.MAX_FINE_BLOCKS); p.end();
      }
    };

    interpIntoChild(cur);
    substep(cur);
    cur = 'b';
    if (hasChild) {
      S_Advance(level + 1, enc);
      averageFromChild(cur);
      interpIntoChild(cur);
    }
    // Legacy same-level fine-fine refresh (?ghostcopy=1 only). The default
    // path needs no pass here: substep B's own gather reaches into the
    // neighbour tile directly, so it reads the neighbour's post-`average`
    // interior rather than a copy taken before that average landed. See the
    // DIRECT_GHOST override in shaders/amr_step1.wgsl.
    if (GHOST_COPY) fineFineRefresh();
    substep(cur);
    cur = 'a';
    if (hasChild) {
      S_Advance(level + 1, enc);
      averageFromChild(cur);
    }
  }

  function dispatchMacroStep(enc) {
    const interpInitBG = useB ? interpInitBG_readB : interpInitBG_readA;

    if (autoRefine && macroStepCounter % REFINE_EVERY === 0) {
      for (let m = 1; m < N_LEVELS; m++) {
        enc.clearBuffer(pools[m].newlyActivatedBuf);
      }

      const crit = enc.beginComputePass(); crit.setPipeline(criterionPL); crit.setBindGroup(0, criterionBG); crit.dispatchWorkgroups(WGX, WGY); crit.end();
      for (let m = 1; m < N_LEVELS - 1; m++) {
        const c = enc.beginComputePass(); c.setPipeline(criterionPoolPLs[m]); c.setBindGroup(0, criterionPoolBGs[m]); c.dispatchWorkgroups(2, 2, pools[m].MAX_FINE_BLOCKS); c.end();
      }

      const FIXED_POINT_ITERS = REFINE_ITERS_OVERRIDE > 0 ? REFINE_ITERS_OVERRIDE
        : Math.max(1, N_LEVELS - 1);
      for (let iter = 0; iter < FIXED_POINT_ITERS; iter++) {
        // Zero the convergence counters before the LAST iteration only, so what
        // they hold afterwards describes exactly that iteration. A nonzero
        // `granted` then means the loop was still creating tiles when its fixed
        // iteration count ran out -- the topology handed to the solver has
        // outstanding refinement. See debugReadDiag().
        if (DIAG && iter === FIXED_POINT_ITERS - 1) enc.clearBuffer(diagBuf, 12, 20);
        for (let m = N_LEVELS - 1; m >= 1; m--) {
          if (m === 1) {
            const p = enc.beginComputePass(); p.setPipeline(manageCoarsenPL); p.setBindGroup(0, manageBG); p.dispatchWorkgroups(WG_MANAGE); p.end();
          } else {
            const parentLevel = m - 1;
            const wg = Math.ceil(pools[m].MAX_FINE_BLOCKS / 64);
            const p = enc.beginComputePass(); p.setPipeline(managePoolCoarsenPLs[parentLevel]); p.setBindGroup(0, managePoolBGs[parentLevel]); p.dispatchWorkgroups(wg); p.end();
          }
        }
        for (let m = 1; m < N_LEVELS; m++) {
          if (m === 1) {
            const p = enc.beginComputePass(); p.setPipeline(manageRefinePL); p.setBindGroup(0, manageBG); p.dispatchWorkgroups(WG_MANAGE); p.end();
          } else {
            const parentLevel = m - 1;
            const wg = Math.ceil(pools[parentLevel].MAX_FINE_BLOCKS / 64);
            const p = enc.beginComputePass(); p.setPipeline(managePoolRefinePLs[parentLevel]); p.setBindGroup(0, managePoolBGs[parentLevel]); p.dispatchWorkgroups(wg); p.end();
          }
        }
      }

      const init = enc.beginComputePass(); init.setPipeline(interpInitPL); init.setBindGroup(0, interpInitBG); init.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); init.end();
      for (let m = 2; m < N_LEVELS; m++) {
        const pool = pools[m];
        const p = enc.beginComputePass(); p.setPipeline(interpPoolParentInitPL); p.setBindGroup(0, pool.interpPoolParentBG_readA); p.dispatchWorkgroups(WGX1, WGY1, pool.MAX_FINE_BLOCKS); p.end();
      }
    }
    macroStepCounter++;

    S_Advance(0, enc);

    useB = !useB;
  }

  function resetSim() {
    writeF(f_a, initF(), NCELLS);
    writeF(pools[1].finePoolF_a, initFPool(), MAX_FINE_BLOCKS * NCELLS1);
    device.queue.writeBuffer(cardStateBuf, 0, initCardState());
    device.queue.writeBuffer(pools[1].blockSlotBuf, 0, new Int32Array(NBLOCKS).fill(-1));
    device.queue.writeBuffer(pools[1].slotToBlockBuf, 0, new Int32Array(MAX_FINE_BLOCKS).fill(-1));
    device.queue.writeBuffer(pools[1].freeListBuf, 0, new Int32Array(MAX_FINE_BLOCKS).map((_, i) => i));
    device.queue.writeBuffer(pools[1].freeCountBuf, 0, new Int32Array([MAX_FINE_BLOCKS]));
    for (let c = 2; c < N_LEVELS; c++) {
      const pool = pools[c];
      writeF(pool.finePoolF_a, initFPool(pool.MAX_FINE_BLOCKS), pool.MAX_FINE_BLOCKS * NCELLS1);
      device.queue.writeBuffer(pool.blockSlotBuf, 0, new Int32Array(pool.NBLOCKS).fill(-1));
      device.queue.writeBuffer(pool.slotToBlockBuf, 0, new Int32Array(pool.MAX_FINE_BLOCKS).fill(-1));
      const freeQuads = Array.from({ length: pool.MAX_FINE_BLOCKS / 4 }, (_, i) => i);
      device.queue.writeBuffer(pool.freeListBuf, 0, new Int32Array(freeQuads));
      device.queue.writeBuffer(pool.freeCountBuf, 0, new Int32Array([freeQuads.length]));
    }
    macroStepCounter = 0;
    useB = false;
    step = 0;
  }

  async function readPoolIndirection(level = 1) {
    const pool = pools[level];
    const stageBlockSlot = device.createBuffer({ size: pool.NBLOCKS * 4, usage: U.MAP_READ | U.COPY_DST });
    const stageSlotToBlock = device.createBuffer({ size: pool.MAX_FINE_BLOCKS * 4, usage: U.MAP_READ | U.COPY_DST });
    const enc = device.createCommandEncoder();
    enc.copyBufferToBuffer(pool.blockSlotBuf, 0, stageBlockSlot, 0, pool.NBLOCKS * 4);
    enc.copyBufferToBuffer(pool.slotToBlockBuf, 0, stageSlotToBlock, 0, pool.MAX_FINE_BLOCKS * 4);
    device.queue.submit([enc.finish()]);
    await Promise.all([stageBlockSlot.mapAsync(GPUMapMode.READ), stageSlotToBlock.mapAsync(GPUMapMode.READ)]);
    const blockSlot = new Int32Array(stageBlockSlot.getMappedRange()).slice();
    const slotToBlock = new Int32Array(stageSlotToBlock.getMappedRange()).slice();
    stageBlockSlot.unmap(); stageSlotToBlock.unmap();
    stageBlockSlot.destroy(); stageSlotToBlock.destroy();
    return { blockSlot, slotToBlock };
  }

  async function setAutoRefine(v) { autoRefine = !!v; }

  async function debugListActiveBlocks(level = 1) {
    const pool = pools[level];
    const { blockSlot } = await readPoolIndirection(level);
    const active = [];
    for (let blockID = 0; blockID < pool.NBLOCKS; blockID++) {
      if (blockSlot[blockID] !== -1) {
        active.push({ bx: blockID % pool.NBX, by: Math.floor(blockID / pool.NBX), slot: blockSlot[blockID] });
      }
    }
    return active;
  }

  // Same border-aware 2:1-balance check as main-channel-amr.js's own
  // debugCheck21Balance (verbatim -- purely structural, no scenario
  // dependence at all).
  // Every level's blockSlot copied in ONE command encoder and ONE submit, so
  // all levels come from the SAME GPU state.
  //
  // BUGFIX: debugCheck21Balance used to call debugListActiveBlocks(m) in a
  // loop, and each of those does its own submit + mapAsync round trip. While
  // the sim is RUNNING (liveMode, i.e. any ordinary browser session) the
  // render loop keeps submitting macro-steps between those round trips, so
  // level 1 was read at one instant and level 2 at a later one -- across, in
  // general, one or more REFINE_EVERY refinement rounds. A tile coarsened out
  // of level 1 after the level-1 read, or refined into level 2 before the
  // level-2 read, then reads back as a depth-2-next-to-depth-0 pair that
  // never existed at any single instant: a torn snapshot reported as a 2:1
  // violation.
  //
  // This is why the artifact only ever showed up at levels>=3: at levels=2
  // the loop runs exactly once, so there is only one readback and nothing to
  // tear against. That made it look like "the second refinement octave breaks
  // 2:1 balance" when what actually changed was the number of readbacks.
  // Live-verified on index-amr.html?levels=3 by alternating protocols on one
  // page: sampling while live reported violations in 2 of 8 samples, while
  // the paused read taken immediately after each of those was clean every
  // time (0 of 8). Reading every level in one submit makes the check sound in
  // both modes; tools/lib/amr-invariants.js pauses first and so was never
  // affected either way.
  async function readAllBlockSlots() {
    const stages = [];
    const enc = device.createCommandEncoder();
    for (let m = 1; m < N_LEVELS; m++) {
      const pool = pools[m];
      const stage = device.createBuffer({ size: pool.NBLOCKS * 4, usage: U.MAP_READ | U.COPY_DST });
      enc.copyBufferToBuffer(pool.blockSlotBuf, 0, stage, 0, pool.NBLOCKS * 4);
      stages.push({ m, stage, pool });
    }
    device.queue.submit([enc.finish()]);
    await Promise.all(stages.map(s => s.stage.mapAsync(GPUMapMode.READ)));
    const sets = {};
    for (const { m, stage, pool } of stages) {
      const blockSlot = new Int32Array(stage.getMappedRange()).slice();
      stage.unmap();
      stage.destroy();
      const active = new Set();
      for (let blockID = 0; blockID < pool.NBLOCKS; blockID++) {
        if (blockSlot[blockID] !== -1) active.add(`${blockID % pool.NBX},${Math.floor(blockID / pool.NBX)}`);
      }
      sets[m] = active;
    }
    return sets;
  }

  async function debugCheck21Balance() {
    const NBX_ = {}, NBY_ = {};
    // One coherent multi-level snapshot -- see readAllBlockSlots.
    const activeSets = await readAllBlockSlots();
    for (let m = 1; m < N_LEVELS; m++) {
      NBX_[m] = pools[m].NBX; NBY_[m] = pools[m].NBY;
    }
    function hasChild(m, bx, by) {
      return m + 1 < N_LEVELS && activeSets[m + 1].has(`${bx * 2},${by * 2}`);
    }
    function ancestorDepth(m, bx, by) {
      let level = m, x = bx, y = by;
      while (level >= 1) {
        if (activeSets[level].has(`${x},${y}`)) return level;
        x = Math.floor(x / 2); y = Math.floor(y / 2);
        level--;
      }
      return 0;
    }
    const EDGE_CHILDREN = { N: [[0, 0], [1, 0]], S: [[0, 1], [1, 1]], E: [[1, 0], [1, 1]], W: [[0, 0], [0, 1]] };
    const OPPOSITE = { N: 'S', S: 'N', E: 'W', W: 'E' };
    function borderMaxDepth(m, bx, by, edge) {
      if (!hasChild(m, bx, by)) return m;
      let maxD = m;
      for (const [dx, dy] of EDGE_CHILDREN[edge]) {
        maxD = Math.max(maxD, borderMaxDepth(m + 1, bx * 2 + dx, by * 2 + dy, edge));
      }
      return maxD;
    }
    const violations = [];
    const NEIGHBOR_OFFSETS = [['N', 0, -1], ['S', 0, 1], ['E', 1, 0], ['W', -1, 0]];
    for (let m = 1; m < N_LEVELS; m++) {
      for (const key of activeSets[m]) {
        const [bx, by] = key.split(',').map(Number);
        if (hasChild(m, bx, by)) continue;
        for (const [edge, dx, dy] of NEIGHBOR_OFFSETS) {
          const nbx = (bx + dx + NBX_[m]) % NBX_[m];
          const nby = (by + dy + NBY_[m]) % NBY_[m];
          const nDepth = activeSets[m].has(`${nbx},${nby}`)
            ? borderMaxDepth(m, nbx, nby, OPPOSITE[edge])
            : ancestorDepth(m, nbx, nby);
          if (Math.abs(m - nDepth) > 1) violations.push({ level: m, bx, by, myDepth: m, neighbor: [nbx, nby], nDepth, edge });
        }
      }
    }
    return { ok: violations.length === 0, violations };
  }

  // No body -- HAS_BODY=0 means isNearBody(At) is unconditionally false in
  // every manage shader, so there's nothing for a geometry-coverage check
  // to assert. Trivially passing.
  async function debugCheckGeometryCoverage() {
    return { ok: true, violations: [] };
  }

  async function debugReadCardState() {
    const stage = device.createBuffer({ size: 104, usage: U.MAP_READ | U.COPY_DST });
    const enc = device.createCommandEncoder();
    enc.copyBufferToBuffer(cardStateBuf, 0, stage, 0, 104);
    device.queue.submit([enc.finish()]);
    await stage.mapAsync(GPUMapMode.READ);
    const d = Array.from(new Float32Array(stage.getMappedRange()));
    stage.unmap();
    stage.destroy();
    const keys = ['cx','cy','theta','vx','vy','omega','fx','fy','tz','mass','i_body','g_eff','a','b','v_max','o_max','cx_old','cy_old','th_old','tau','y_total','x_total','off_x','off_y','off_x_old','off_y_old'];
    const out = {};
    keys.forEach((k,i) => out[k] = d[i]);
    return out;
  }

  async function debugStepSync(n) {
    liveMode = false;
    for (let k = 0; k < n; k += STEPS_PER_FRAME) {
      const enc = device.createCommandEncoder();
      for (let s = 0; s < STEPS_PER_FRAME; s++) dispatchMacroStep(enc);
      device.queue.submit([enc.finish()]);
      await device.queue.onSubmittedWorkDone();
      step += STEPS_PER_FRAME;
    }
    return { step };
  }

  const stagingVel = device.createBuffer({ size: NCELLS * 2 * 4, usage: U.MAP_READ | U.COPY_DST });

  // Full 2D velocity field. Reads velBuf directly -- L0's own step kernel
  // writes every cell every step regardless of refinement, and the
  // average pass (S_Advance) overwrites any refined block's L0 cells with
  // the finer level's restricted value, so velBuf always holds the
  // finest-available data even in a partially-refined domain (same
  // reasoning as main-channel-amr.js's readProfile). Block-major indexing
  // (cellIndexJS), not flat row-major -- see amr_step.wgsl.
  async function readField() {
    const enc = device.createCommandEncoder();
    enc.copyBufferToBuffer(velBuf, 0, stagingVel, 0, NCELLS * 2 * 4);
    device.queue.submit([enc.finish()]);
    await stagingVel.mapAsync(GPUMapMode.READ);
    const vel = new Float32Array(stagingVel.getMappedRange()).slice();
    stagingVel.unmap();
    const ux = new Array(NCELLS), uy = new Array(NCELLS);
    for (let y = 0; y < H; y++) {
      for (let x = 0; x < W; x++) {
        const cell = cellIndexJS(x, y);
        const flat = y * W + x;
        ux[flat] = vel[cell * 2];
        uy[flat] = vel[cell * 2 + 1];
      }
    }
    return { ux, uy };
  }

  function getLevelPoolSizes() {
    return pools.slice(1).map(p => ({
      level: p.level,
      NBX: p.NBX, NBY: p.NBY, NBLOCKS: p.NBLOCKS,
      MAX_FINE_BLOCKS: p.MAX_FINE_BLOCKS,
    }));
  }

  window.__CYL = {
    setLive: (v) => { liveMode = !!v; },
    isLive: () => liveMode,
    reset: resetSim,
    getStep: () => step,
    getDims: () => ({ W, H, N }),
    getParams: () => ({ N, W, H, TAU, U0, nu: nuFromTau(TAU), kx: KX, ky: KY, td: tdFromNu(nuFromTau(TAU)) }),
    readField,
    debugStepSync,
    debugReadCardState,
    debugCheck21Balance,
    debugCheckGeometryCoverage,
    debugListActiveBlocks,
    setAutoRefine,
    isAutoRefine: () => autoRefine,
    getBlockGridDims: () => ({ NBX, NBY, RB, GHOST, FB, NCELLS1, MAX_FINE_BLOCKS }),
    getRefineParams: () => ({
      REFINE_EVERY, REFINE_THRESH, COARSEN_THRESH, FORCE_REFINE_MARGIN, FORCE_REFINE_LOOKAHEAD,
      perLevel: Array.from({ length: N_LEVELS - 1 }, (_, i) => ({ childLevel: i + 1, ...paramsForChildLevel(i + 1) })),
    }),
    getNumLevels: () => N_LEVELS,
    getLevelPoolSizes,
    tauAtLevel,
  };

  async function frame() {
    try {
      if (!liveMode) {
        requestAnimationFrame(() => frame().catch(handleErr));
        return;
      }

      device.pushErrorScope('validation');
      const enc = device.createCommandEncoder();

      for (let s = 0; s < STEPS_PER_FRAME; s++) dispatchMacroStep(enc);
      step += STEPS_PER_FRAME;

      const rp = enc.beginRenderPass({ colorAttachments: [{ view: ctx.getCurrentTexture().createView(), clearValue: { r:0.07, g:0.07, b:0.1, a:1 }, loadOp: 'clear', storeOp: 'store' }]});
      rp.setPipeline(renPL); rp.setBindGroup(0, renBG); rp.draw(6); rp.end();

      device.queue.submit([enc.finish()]);
      device.popErrorScope().then(err => { if (err) handleErr(err); });

      if (performance.now() - lastT > 250) {
        statusEl.textContent = `[AMR] step ${step}  N=${N}  U0=${U0.toFixed(3)}  levels=${N_LEVELS}`;
        lastT = performance.now();
      }

      requestAnimationFrame(() => frame().catch(handleErr));
    } catch (e) {
      handleErr(e);
    }
  }
  frame().catch(handleErr);
}
init().catch(handleErr);
