// AMR validation harness: 2D decaying Taylor-Green vortex, driven by the
// exact same multi-level machinery as main-amr.js/main-channel-amr.js
// (buffer layout, pipelines, S_Advance's recursive dispatch, per-level
// criterion/manage -- none of that is touched here, generated by copying
// main-channel-amr.js and swapping in the scenario-specific pieces below).
// Like the channel-flow harness, there is no body at all (HAS_BODY=0
// everywhere) and no force/torque to integrate, so amr_force*.wgsl/
// amr_physics.wgsl are never dispatched. UNLIKE channel flow, this needs
// no WALL_Y/FORCE_X wiring at all -- the domain is exactly, doubly
// periodic (see main-tgv.js's identical dense-solver rationale), which is
// also the ALREADY-VALIDATED coarse-fine interpolation path every other
// AMR page in this repo already exercises -- none of the wall-adjacent-
// interpolation gap documented in shaders/amr_interp_dense_parent.wgsl's
// header applies here, so autoRefine defaults ON (unlike
// main-channel-amr.js's deliberate default-off).
//
// This is the interesting AMR stress test the channel-flow harness isn't:
// TGV's vorticity varies smoothly but genuinely in SPACE (peak at specific
// phase points, zero at others), so real refinement patterns COULD form
// and evolve as the vortex decays -- exercising coarse-fine interpolation
// accuracy at real, moving interfaces, not just "does the machinery run."
//
// KNOWN GAP, DISCOVERED LIVE (not just theoretical), same "document +
// avoid triggering it" treatment as main-channel-amr.js's own Couette
// finding: a first attempt scaled REFINE_THRESH/COARSEN_THRESH to a
// fraction of this case's own peak vorticity (2*U0*kx at t=0), aiming for
// the "real, localized refinement pattern" described above. At this
// harness's default resolution, TGV's blockCriterion (per-block MAX
// vorticity) turned out to have a sharp cliff, not a smooth gradient, at
// the coarse (8x8-cell) block granularity -- there was no threshold
// producing a partial, localized refined region; it was either ~0 blocks
// active or ~94% of the domain (60/64) refining simultaneously. Live-
// verified: with that large-fraction-simultaneous case, L2rel-vs-analytic
// was 35x worse than the same step count with refinement OFF (3.4% vs.
// 0.097%) immediately after the first refine/coarsen cycle, and KEPT
// GROWING for over 2000 further steps with zero blocks active afterward
// (16.5%, then 19.7%) -- consistent with the coarsen/average step
// (amr_average_f2c.wgsl) leaving some real, persistent inconsistency in
// the coarse buffer when releasing a very large simultaneous batch of
// fine tiles, not a one-time interpolation-smoothing effect that would
// stay bounded. This is genuinely new territory: every other AMR
// scenario validated in this repo (cylinder wake, channel flow) only
// ever refines a SMALL localized fraction of the domain, never anywhere
// close to this scale at once. Root cause not yet isolated. Fix:
// REFINE_THRESH/COARSEN_THRESH default to main-amr.js's own fixed -6/-7
// (see below), which doesn't trigger at all for typical TGV U0/N choices
// -- `?refineThresh=-8` (etc.) opts into the demonstrated-fragile regime
// for further investigation, not for physics validation.
//
// window.__CYL exposes the same shape main-tgv.js's dense harness does
// (reset, getStep, getParams, readField) plus the AMR invariant-sweep
// surface tools/lib/amr-invariants.js needs (debugStepSync returning
// {step}, debugCheck21Balance, debugReadCardState). NOT
// debugCheckGeometryCoverage: this page has no body (HAS_BODY = 0), so
// tools/lib/amr-invariants.js's probe reports it SKIPPED, which is what that
// file's "a missing optional check is reported as skipped, never as a pass"
// design intends. It used to be defined here as a stub returning {ok:true} --
// a green tick standing for nothing, which is exactly what the probe exists
// to avoid.

import { reportFatal, refuseConfig, reportNoWebGPU, reportNoAdapter } from './error-overlay.mjs';
import { tauChainSingularity, tauSingularityMessage, rootCellIndex, rootPoolSpec, denseCellIndex } from './amr2d.mjs';
import { loadShader } from './shader-loader.mjs';
import { packF, unpackF, fWords } from './f-pack.mjs';
import { check21BalanceOnGPU, readConservedTotals, allocLevelPool, writePoolInitialState, readPoolIndirection as readPoolIndirectionOn, listActiveBlocks, readCardState , checkRefinementClosureOnGPU , makeCascadePipelines, encodeCascade, cascadeRoundTrip, makeCascadeSeeds, checkSlotQuadrantsOnGPU, makeRenderBindGroup, renderPoolLevels, MAX_RENDER_POOL_LEVELS, makeAMRLayouts, makeCouplingPipelines, makeLevelBindGroups, makeManageBindGroups, makeScheduler, makeRefineRound, allocRootPool, makeRootPool, seedRootFromDenseF } from './amr2d-gpu.mjs';
// tauAtLevel: extracted to card-params.mjs by B3a-1, which landed the CALL
// in all five AMR pages and this IMPORT in only main-amr.js. The other four
// threw `ReferenceError: tauAtLevelOf is not defined` at init -- but only at
// ?levels>=3, because updateLevelParams's `for (c = 2; c < N_LEVELS; c++)`
// loop is VACUOUS at the levels=2 default every one of them ships. See
// plans/2D-backport.md B4.
import { tauAtLevel as tauAtLevelOf } from './card-params.mjs';
import { EX, EY, WT } from './lattice-2d.mjs';
import { makeCanvasFit } from './canvas-fit.mjs';

const canvas   = document.getElementById('c');
const statusEl = document.getElementById('status');

const urlParams = new URLSearchParams(window.location.search);
// ?f16=1 / ?f16=2: real packed-half storage for `f` -- see shaders/common_fpack.wgsl
// and f-pack.mjs. Wired on EVERY page that consumes those shaders, including
// the ones with no accuracy check of their own: a page that quietly ignored
// ?f16= would make a green `validate-all --extra=f16=1` sweep look like it
// covered ground it never touched, which is the kind of false confidence
// this repo has been bitten by before.
const F16 = urlParams.has('f16') ? (parseInt(urlParams.get('f16')) || 0) : 0;

// ── ?dcpre=1 -- the legacy PRE-collision Dupuis-Chopard transfer factor ──────
// The coarse<->fine transfers rescale the non-equilibrium part of f, and the
// factor that shipped here until plans/2D-backport.md B1 was the textbook
// PRE-collision one -- while every buffer this solver transfers holds f AFTER
// collision, because amr_step.wgsl is a fused pull-stream + collide. At this
// page's default tau = 0.8 the two differ in magnitude AND SIGN (+0.6875
// against -0.25), which is why the analytic decay gate here -- not a Cd/St
// average -- is the instrument that can see it. amr2d.mjs's
// dcRescaleCoarseToFine carries the derivation and tools/test-amr2d.js gates
// both forms.
//
// Both factors live in one build so the defect can be RE-MEASURED rather than
// reconstructed from a checkout -- the same reason ?ghostcopy= and ?f16= are
// still here. It also has no tau = 1 singularity, so it is the escape hatch
// the refusal names.
const DC_PRE = urlParams.has('dcpre') ? (parseInt(urlParams.get('dcpre')) || 0) : 0;






// ── ?ghostcopy=1 -- legacy materialized same-level ghost cells ───────────────
// Default 0: the fine step resolves a source cell that falls outside its tile
// against the owning same-level tile directly (blockSlot), so the
// between-substep fine-fine ghost COPY pass is not encoded at all. Measured
// worth 9.9% of frame GPU time on the desktop and 13.1% on the phone (the pass
// itself was 16.7-17.5%; the fine step gives 3.6-7.5% of that back, since half
// a tile's threads now pull from another slot's memory) -- see
// plans/perf-characterization.md's "The one lead left" for the full
// decomposition on both devices.
//
// 1 restores the old path exactly (clamp at the slot's own buffer edge, plus
// the copy pass), so the two can be A/B'd for both speed and physics on one
// build: `node tools/validate-all.js --extra=ghostcopy=1` runs the whole
// validation sweep against the legacy path.
const GHOST_COPY = urlParams.has('ghostcopy') ? (parseInt(urlParams.get('ghostcopy')) || 0) : 0;

// ── ?diag=1 -- refinement convergence counters ──────────────────────────────
// Makes the refine round's fixed-point loop report whether it actually
// SETTLED, instead of just running out of iterations. Off by default and
// zero-cost when off: the DIAG override gates every atomic.
const DIAG = urlParams.has('diag') ? (parseInt(urlParams.get('diag')) || 0) : 0;

let resLog2 = parseInt(urlParams.get('res')) || 6;
// Floor of 5 (N=32, NBX=4) -- same structural minimum as main-channel-
// amr.js (more than one coarse block per axis), not the cylinder
// harness's blockage-domain-derived 7.
if (resLog2 < 5) resLog2 = 5;
if (resLog2 > 9) resLog2 = 9;

let N = 1 << resLog2;
let W = N, H = N;
let NCELLS = W * H;

let U0 = parseFloat(urlParams.get('u0')) || 0.04;
let TAU = parseFloat(urlParams.get('tau')) || 0.8;

function nuFromTau(tau) { return (tau - 0.5) / 3; }

const KX = 2 * Math.PI / N;
const KY = 2 * Math.PI / N;

function tdFromNu(nu) { return 1 / (nu * (KX * KX + KY * KY)); }

const GHOST = 2;
const BLOCK = 8;
const RB = BLOCK;
const FB = RB * 2 + 2 * GHOST;
const NCELLS1 = FB * FB;
// ── ?demandCascade=1 -- the growth half of Milestone 9's refine cascade ────
// plans/AMR-multilevel.md specifies: "a quad may only refine to level m+1 if
// its same-level neighbors are already present; if a neighbor is more than one
// level coarser, force THAT neighbor to refine first (recursively, if the gap
// is >1)". Only the veto half was ever implemented, so a criterion-driven
// refine can be vetoed forever by a neighbour that would only ever have been
// created BY that refine. Measured live on index-amr.html: level 2 never
// extends past the geometry halo into the wake, which pins the L1/L2 boundary
// a few cells off the body so every shed vortex crosses it right there.
//
// The recursion the plan asks for is a poor GPU fit, but the depth is known up
// front and the fixed-point loop below is the bounded equivalent: growth
// advances one level per iteration and the loop already runs N_LEVELS-1 times,
// which is the exact bound. See shaders/amr_manage.wgsl's level2Wanted for the
// mechanism, why it is a union with (not a replacement for) the existence-based
// cascade that superseded it, and why it stops at the L0->L1 hop.
//

// The 2:1 rule is ONE closure on the want set (plans/2D-backport.md B2):
// decide -> shaders/amr_cascade.wgsl -> coarsen/refine, once. ?cascade=0 kept
// the old per-pass path alongside it for one commit so the difference could be
// measured (B2-2c: corner 2:1 violations 13 -> 0, level 2's x-extent 80 -> 160
// L0 units on this page); B2-2d deleted it.

const MAX_FINE_BLOCKS = urlParams.has('maxFineBlocks') ? parseInt(urlParams.get('maxFineBlocks')) : 128;
const NBX = W / BLOCK, NBY = H / BLOCK, NBLOCKS = NBX * NBY;

const N_LEVELS = urlParams.has('levels') ? parseInt(urlParams.get('levels')) : 2;
// refuseConfig, not throw: this runs at module scope, where
// init().catch(handleErr) can never see it -- see error-overlay.mjs.
if (N_LEVELS < 2) refuseConfig(statusEl, `?levels=${N_LEVELS} invalid -- must be >= 2 (L0 + at least one fine level)`);
// U6: and the renderer's own ceiling, refused BEFORE anything is allocated for
// a configuration that cannot be drawn. A cap that silently drops the finest
// level is the defect U6 exists to fix -- at ?levels=4 a level-3 tile used to
// be refined, solved, force-reduced and then drawn as its level-2 parent, and
// `tools/validate-render-levels.js` measured the picture as BYTE-IDENTICAL
// after perturbing that level's whole velocity pool.
if (N_LEVELS - 1 > MAX_RENDER_POOL_LEVELS) {
  refuseConfig(statusEl, `?levels=${N_LEVELS} needs ${N_LEVELS - 1} pool levels in the renderer, `
    + `which binds ${MAX_RENDER_POOL_LEVELS} (shaders/amr_render.wgsl's walk). Raising it means one `
    + `more binding pair there, in amr2d-gpu.mjs's RENDER_LEVEL_BINDINGS, and in every page's renBGL.`);
}

// Vorticity-driven refinement -- REFINE_THRESH/COARSEN_THRESH default to
// main-amr.js's own fixed -6/-7 (unchanged, NOT scaled to this case's own
// peak vorticity) -- see this file's own header for why a scaled default
// was tried and reverted. At typical U0/N choices (e.g. the default
// U0=0.04, N=64: peak vorticity 2*U0*kx=0.0079, log2~=-7.0), -6/-7 sits
// comfortably above that peak, so refinement doesn't trigger by default --
// deliberately conservative, mirroring main-channel-amr.js's own
// autoRefine-off-by-default posture, just implemented as "thresholds that
// don't fire" instead of "autoRefine off" (autoRefine itself stays ON
// here, since the machinery is safe to RUN, just not yet safe to trigger
// at TGV's own vorticity scale by default). FORCE_REFINE_MARGIN/LOOKAHEAD
// are wired through structurally (every manage pipeline expects them) but
// never gate anything: HAS_BODY=0 makes isNearBody/isNearBodyAt
// unconditionally false.
const REFINE_EVERY = urlParams.has('refineEvery') ? parseInt(urlParams.get('refineEvery')) : 16;
const REFINE_THRESH = urlParams.has('refineThresh') ? parseFloat(urlParams.get('refineThresh')) : -6;
const COARSEN_THRESH = urlParams.has('coarsenThresh') ? parseFloat(urlParams.get('coarsenThresh')) : -7;
const FORCE_REFINE_MARGIN = urlParams.has('forceRefineMargin') ? parseFloat(urlParams.get('forceRefineMargin')) : 8;
const FORCE_REFINE_LOOKAHEAD = urlParams.has('forceRefineLookahead') ? parseFloat(urlParams.get('forceRefineLookahead')) : REFINE_EVERY;

function cellSizeL0AtLevel(m) { return 2 ** -m; }

// Per-child-level REFINE_THRESH/COARSEN_THRESH/FORCE_REFINE_MARGIN/
// FORCE_REFINE_LOOKAHEAD override -- see main-channel-amr.js's identical
// function.
function paramsForChildLevel(childLevel) {
  if (childLevel === 1) {
    return { REFINE_THRESH, COARSEN_THRESH, FORCE_REFINE_MARGIN, FORCE_REFINE_LOOKAHEAD };
  }
  const get = (name, base) => urlParams.has(`${name}${childLevel}`) ? parseFloat(urlParams.get(`${name}${childLevel}`)) : base;
  return {
    REFINE_THRESH: get('refineThresh', REFINE_THRESH),
    COARSEN_THRESH: get('coarsenThresh', COARSEN_THRESH),
    FORCE_REFINE_MARGIN: get('forceRefineMargin', FORCE_REFINE_MARGIN),
    FORCE_REFINE_LOOKAHEAD: get('forceRefineLookahead', FORCE_REFINE_LOOKAHEAD),
  };
}

const resSlider = document.getElementById('slider-RES');
const resVal    = document.getElementById('val-RES');
resSlider.value = resLog2;
resVal.textContent = N;
resSlider.onchange = () => {
  const url = new URL(window.location);
  url.searchParams.set('res', resSlider.value);
  window.location.href = url.href;
};
resSlider.oninput = () => {
  resVal.textContent = 1 << parseInt(resSlider.value);
};

const u0Slider = document.getElementById('slider-U0');
const u0Val    = document.getElementById('val-U0');
u0Slider.value = U0;
u0Val.textContent = U0.toFixed(3);
u0Slider.onchange = () => {
  const url = new URL(window.location);
  url.searchParams.set('u0', u0Slider.value);
  window.location.href = url.href;
};
u0Slider.oninput = () => {
  u0Val.textContent = parseFloat(u0Slider.value).toFixed(3);
};

// The D2Q9 basis, from the ONE place it is derived -- lattice-2d.mjs, which
// also generates shaders/common_lattice.wgsl. Typed out here (and in nine
// sibling pages) until 2026-09-14, in f64 EXACT FRACTIONS while the shader
// held eight-digit f32 decimals: the host built its initial condition from
// weights the GPU did not have. WT is now the shader's own f32 values.
// EX/EY were already identical everywhere and are unchanged.
function feq(rho, ux, uy, i) {
  const eu = EX[i]*ux + EY[i]*uy;
  return WT[i] * rho * (1 + eu*3 + eu*eu*4.5 - (ux*ux+uy*uy)*1.5);
}

// Exact analytic field at t=0 -- see main-tgv.js's identical derivation.
//
// INDEXED WITH `icCellIndex`, NOT `cellIndexJS`, AND THE TWO ARE DIFFERENT
// LAYOUTS SINCE U7-6f. `initF()`'s output is the IC as the SEEDER wants it --
// dense block8 -- and `seedRootFromDenseF` permutes it into root tiles;
// `cellIndexJS` is where a level-0 cell lives ON THE GPU afterwards, which is
// the root pool's tile-major index. They were the same function while level 0
// was a dense grid.
//
// Seeding at the wrong layout doesn't error (both are just NCELLS-length
// arrays) -- it silently scrambles which physical (x,y) each cell's analytic
// value lands on, corrupting the initial condition into something with no
// resemblance to the intended field. That is the whole reason they are named
// apart rather than one being the default.
function analyticFieldAtZero() {
  const CS2 = 1 / 3;
  const ux = new Float64Array(NCELLS), uy = new Float64Array(NCELLS), rho = new Float64Array(NCELLS);
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const c = icCellIndex(x, y);
      const cx = Math.cos(KX * x), sx = Math.sin(KX * x);
      const cy = Math.cos(KY * y), sy = Math.sin(KY * y);
      ux[c] = -U0 * cx * sy;
      uy[c] = U0 * (KX / KY) * sx * cy;
      const p = -(U0 * U0 / 4) * ((KY / KX) * Math.cos(2 * KX * x) + (KX / KY) * Math.cos(2 * KY * y));
      rho[c] = 1 + p / CS2;
    }
  }
  return { ux, uy, rho };
}

// Seed L0 at the equilibrium distribution for the exact analytic t=0
// field -- see main-tgv.js's identical rationale. Pool levels start
// entirely inactive (blockSlot=-1 everywhere) and get filled from L0 via
// the normal coarse->fine interpolation path the moment refinement first
// activates them, same as every other AMR harness here -- there's nothing
// to seed there directly, so initFPool keeps the quiescent-equilibrium
// fill (harmless: inactive slots are never read).
function initF() {
  const { ux, uy, rho } = analyticFieldAtZero();
  const f = new Float32Array(NCELLS * 9);
  for (let c = 0; c < NCELLS; c++) {
    for (let i = 0; i < 9; i++) f[i * NCELLS + c] = feq(rho[c], ux[c], uy[c], i);
  }
  return f;
}
function initFPool(maxBlocks = MAX_FINE_BLOCKS) {
  const NPOOL = maxBlocks * NCELLS1;
  const f = new Float32Array(NPOOL * 9);
  for (let c = 0; c < NPOOL; c++) {
    for (let i = 0; i < 9; i++) f[i * NPOOL + c] = feq(1, 0, 0, i);
  }
  return f;
}

// Dummy CardState: HAS_BODY=0 means every step/manage shader never lets
// these fields affect the fluid (see main-channel-amr.js's identical
// rationale).
function initCardState() {
  const card = new Float32Array(26);
  card[12] = 1; card[13] = 1; // a, b
  card[19] = TAU;
  return card;
}

function handleErr(e) {
  // Status line AND a legible on-page overlay -- see error-overlay.mjs for why
  // the 12px status line alone was not enough.
  reportFatal(statusEl, e);
}

// card-params.mjs owns this rule and tools/test-card-params.js tests it.
// Five pages inlined the same loop -- see plans/2D-backport.md B3a.
const tauAtLevel = (m) => tauAtLevelOf(TAU, m);
// THE INITIAL CONDITION'S OWN LAYOUT: dense block8, which is what
// `seedRootFromDenseF` consumes and permutes into root tiles. amr2d.mjs owns
// the rule (`denseCellIndex`) and tools/lib/field-reconstruct.js's `rawIndex`
// is the decoder scored against it -- restating the four lines here is how U2
// got two agreeing routes over a wrong mapping.
const icCellIndex = (cx, cy) => denseCellIndex({ dims: { W, H } }, cx, cy);

// WHERE A LEVEL-0 CELL LIVES, for the host readbacks below.
//
// It was `shaders/amr_step.wgsl`'s block8 `cellIndex()` until U7-6f, because
// level 0 was a dense grid in that layout. Level 0 is the ROOT POOL now --
// 2*RB-square tiles, row-major within a tile, ringless -- so the mapping is
// amr2d.mjs's `rootCellIndex`, which is the same function the shader and the
// snapshot decoder use. THE ROOT'S INDIRECTION IS THE IDENTITY, which is what
// lets this be a pure function of (x, y) with no blockSlot lookup.
const cellIndexJS = (cx, cy) => rootCellIndex({ dims: { W, H }, rb: RB }, cx, cy);

async function init() {
  if (!navigator.gpu) { reportNoWebGPU(statusEl); return; }
  const adapter = await navigator.gpu.requestAdapter();
  if (!adapter) { reportNoAdapter(statusEl); return; }

  const DEFAULT_MAX_STORAGE_BINDING = 128 * 1024 * 1024;
  const DEFAULT_MAX_BUFFER_SIZE = 256 * 1024 * 1024;
  const neededBufferBytes = NCELLS * 9 * 4;
  if (neededBufferBytes > adapter.limits.maxStorageBufferBindingSize) {
    const mib = (b) => (b / 1048576).toFixed(0);
    statusEl.textContent = `error: ${W}x${H} needs a ${mib(neededBufferBytes)} MiB buffer binding, this GPU's max is ${mib(adapter.limits.maxStorageBufferBindingSize)} MiB`;
    return;
  }
  const NEEDED_STORAGE_BUFFERS_PER_STAGE = 16;
  if (NEEDED_STORAGE_BUFFERS_PER_STAGE > adapter.limits.maxStorageBuffersPerShaderStage) {
    statusEl.textContent = `error: needs ${NEEDED_STORAGE_BUFFERS_PER_STAGE} storage buffers per shader stage, this GPU's max is ${adapter.limits.maxStorageBuffersPerShaderStage}`;
    return;
  }
  const requiredLimits = {
    maxStorageBufferBindingSize: Math.min(Math.max(neededBufferBytes, DEFAULT_MAX_STORAGE_BINDING), adapter.limits.maxStorageBufferBindingSize),
    maxBufferSize: Math.min(Math.max(neededBufferBytes, DEFAULT_MAX_BUFFER_SIZE), adapter.limits.maxBufferSize),
    maxStorageBuffersPerShaderStage: NEEDED_STORAGE_BUFFERS_PER_STAGE,
  };
  const device = await adapter.requestDevice({ requiredLimits });

  device.pushErrorScope('validation');

  const ctx = canvas.getContext('webgpu');
  const fmt = navigator.gpu.getPreferredCanvasFormat();

  // Canvas sizing and swapchain reconfiguration -- see canvas-fit.mjs,
  // which carries the reasoning for the changed-size guard (it was ten
  // identical copies of it).
  const resize = makeCanvasFit({ canvas, ctx, device, format: fmt });
  window.addEventListener('resize', resize);
  resize();

  const U = GPUBufferUsage;
  // ?diag=1 counters -- 8 u32 slots, read+zeroed via debugReadDiag().
  const diagBuf = device.createBuffer({ size: 8 * 4, usage: U.STORAGE | U.COPY_SRC | U.COPY_DST });
  // DEAD (born dead): f12528b added this buffer to all five pages and the
  // debugReadDiag READER to two. Nothing here can read it, which is why
  // amr-invariants.js's pool-starvation gate does not run on this page. See
  // plans/uniform-levels.md "U7-6f -- WHAT IT LEFT BEHIND".
  const diagReadBuf = device.createBuffer({ size: 8 * 4, usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ });
  const dummyBlockSlotBuf = device.createBuffer({ size: 4, usage: U.STORAGE | U.COPY_DST });
  device.queue.writeBuffer(dummyBlockSlotBuf, 0, new Int32Array([-1]));

  // See main-amr.js's copy for the rationale: the GPU buffer holds packed
  // half pairs under F16, everything else speaks f32 plane-major, and these
  // two are the only places the two meet.
  const writeF = (buf, f32, ncells) => {
    const src = packF(f32, ncells, F16);
    device.queue.writeBuffer(buf, 0, src.buffer, src.byteOffset, ncells * fWords(F16) * 4);
  };
  const readF = (mapped, ncells) =>
    F16 ? unpackF(new Uint32Array(mapped), ncells, true) : new Float32Array(mapped).slice();

  const cardStateBuf = device.createBuffer({ size: 104, usage: U.STORAGE | U.COPY_DST | U.COPY_SRC });

  const pools = [undefined]; // pools[0] unused unless ?rootpool=1 makes L0 a level
  pools[0] = allocRootPool(device, U, { W, H, RB });
  {
    let curNBX = NBX, curNBY = NBY;
    for (let m = 1; m < N_LEVELS; m++) {
      const maxFineBlocks = m === 1
        ? MAX_FINE_BLOCKS
        : (urlParams.has(`maxFineBlocks${m}`) ? parseInt(urlParams.get(`maxFineBlocks${m}`)) : 128);
      // EVERY level allocates in QUADS, level 1 included since the root
      // became its parent (U5-4) and unconditionally since U7-6f.
      const pool = allocLevelPool(device, U, m, curNBX, curNBY, maxFineBlocks, NCELLS1);
      writeF(pool.finePoolF_a, initFPool(maxFineBlocks), maxFineBlocks * NCELLS1);
      pools.push(pool);
      curNBX *= 2; curNBY *= 2;
    }
  }

  device.queue.writeBuffer(cardStateBuf, 0, initCardState());
  // THE ROOT'S INITIAL FIELD, FROM THIS PAGE'S OWN IC (U7-6f). `initF()` is
  // built in dense block8 order -- the layout the IC has always been written
  // in, and the one the reference pages' own grids still use -- and the seeder
  // permutes it into root tiles on the host. See seedRootFromDenseF, which is
  // the one statement of it, shared with the other four AMR pages. Called at
  // init, at reset and at a pre-version-7 snapshot load, never per frame.
  const seedRootFrom = (fDense) => seedRootFromDenseF(device, pools, fDense, { W, H, RB, writeF });
  // resetSim() is NOT called at page load, so this is a separate seed call
  // site and not a duplicate of the one in resetSim().
  seedRootFrom(initF());

  // The ROOT gets one too. `parentTau` is deliberately left at 0: the root's
  // pipeline sets OWN_TAU, so that field is never read, and writing a
  // plausible value there would create a second source of truth.
  for (let c = 0; c < N_LEVELS; c++) {
    const pool = pools[c];
    if (!pool) continue;
    pool.levelParamsBuf = device.createBuffer({ size: 32, usage: U.UNIFORM | U.COPY_DST });
    const staticBuf = new ArrayBuffer(32);
    const staticDv = new DataView(staticBuf);
    staticDv.setUint32(0, pool.NBX, true);
    staticDv.setUint32(4, pool.NBY, true);
    staticDv.setFloat32(12, cellSizeL0AtLevel(c), true);
    // The diffuse band, in units of THIS level's dx -- a per-level uniform
    // since B3-1's follow-up, not the compile-time K_EPS override the fine
    // step used to carry. One pipeline now serves every level, so an override
    // could only ever say one thing for the whole hierarchy. See
    // shaders/amr_step1.wgsl's get_chi.
    staticDv.setFloat32(20, 1.5, true);
    staticDv.setUint32(16, (c + 1) < N_LEVELS ? 1 : 0, true);
    device.queue.writeBuffer(pool.levelParamsBuf, 0, staticBuf);
  }
  function updateLevelParams() {
    // tau = 1 IS A REAL SINGULARITY for the post-collision transfer -- refuse
    // it, do not divide by it. See amr2d.mjs's tauChainSingularity. Reachable
    // here by hand: ?tau=0.75 puts level 1 exactly on 1, and ?tau=1 level 0.
    const sing = DC_PRE === 0 ? tauChainSingularity(TAU, N_LEVELS) : null;
    if (sing) refuseConfig(statusEl, tauSingularityMessage(sing));
    for (let c = 1; c < N_LEVELS; c++) {
      device.queue.writeBuffer(pools[c].levelParamsBuf, 8, new Float32Array([tauAtLevel(c - 1)]));
    }
  }
  updateLevelParams();

  const overlaySlider = document.getElementById('slider-overlay');
  const overlayValEl = document.getElementById('val-overlay');

  const [renSM, interpPoolSM, step1SM, avgPoolSM, criterionPoolSM, managePoolSM] = await Promise.all([
    loadShader(device, 'shaders/amr_render.wgsl'),
    loadShader(device, 'shaders/amr_interp_pool_parent.wgsl'),
    loadShader(device, 'shaders/amr_step1.wgsl'),
    loadShader(device, 'shaders/amr_average_pool_parent.wgsl'),
    loadShader(device, 'shaders/amr_criterion_pool.wgsl'),
    loadShader(device, 'shaders/amr_manage_pool.wgsl'),
  ]);

  // The two modules the shared coupling pipelines need, as one object; plus
  // the fine step, which makeRootPool wants on top of them. It was six until
  // U7-6f deleted the dense-parent interp/average and the dense
  // criterion/manager.
  const modules = { interpPoolSM, avgPoolSM };
  const rootModules = { ...modules, step1SM };

  // U7-0: the EIGHT bind group layouts, from ONE place. They were spelled out
  // inline here and in four other pages, byte-identical in all of them -- see
  // makeAMRLayouts for why that mattered more than the line count, and for the
  // six that went with the dense path at U7-6f.
  //
  // Only what this page uses: it has no body, so no force or physics pass and
  // no phyBGL/force1BGL. makeAMRLayouts builds all eight regardless -- a
  // layout nobody binds costs nothing, and selecting a subset there would
  // reintroduce the per-page variation this removes -- but naming only the
  // consumed ones here keeps "what this page needs" readable.
  const layouts = makeAMRLayouts(device);
  const {
    renBGL, interpPoolParentBGL, avgPoolBGL,
    criterionPoolBGL, managePoolBGL, step1BGL,
  } = layouts;

  const constants = { W, H };

  // Fully periodic, no body, no walls, no force -- see this file's header.
  const stepConstants = { W, H, HAS_BODY: 0, SPONGE_W: 0, F16 };
  const fineConstants = { W, H, RB };

  const step1Constants = { ...stepConstants, RB, DIRECT_GHOST: GHOST_COPY ? 0 : 1 };

  // U7-1: the twelve coupling pipelines, from ONE place. Every page built
  // these identically; see makeCouplingPipelines for what stays per page and
  // why. `couplingConstants` carries the bundles it derived, so the
  // measurement twins and the root-parent variants below are built from the
  // SAME literal the real pipeline used rather than a second copy of it.
  const {
    constants: couplingConstants,
    interpPoolParentPL, interpPoolParentInitPL, interpPoolParentFFPL,
    avgPoolPL,
  } = makeCouplingPipelines(device, layouts, modules, { RB, F16, DC_PRE });

  const step1PL = device.createComputePipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [step1BGL] }),
    compute: { module: step1SM, entryPoint: 'main', constants: { ...step1Constants, F16 } }
  });

  const renPL = device.createRenderPipeline({
    layout: device.createPipelineLayout({ bindGroupLayouts: [renBGL] }),
    vertex: { module: renSM, entryPoint: 'vs_main', constants },
    fragment: { module: renSM, entryPoint: 'fs_main', targets: [{ format: fmt }],
      // U6: THIS PAGE NEVER PASSED A LEVEL OVERRIDE AT ALL, so the shader's
      // HAS_LEVEL2 default of 0 meant level 2 was solved, stepped, force-reduced
      // -- and never drawn. Three of the five AMR pages were in that state.
      // U7-6b: ROOT_IS_POOL must match what makeRenderBindGroup put on binding
      // 0 -- see renderRootIsPool, which is the single statement of that rule.
      constants: { ...fineConstants, N_POOL_LEVELS: renderPoolLevels(N_LEVELS) } },
    primitive: { topology: 'triangle-list' },
  });
  // plans/2D-backport.md B2: the 2:1 closure's own pipelines. Built but
  // NOT yet in dispatchMacroStep -- see debugCascadeRoundTrip.
  const cascadeSM = await loadShader(device, 'shaders/amr_cascade.wgsl');
  const cascade = makeCascadePipelines(device, cascadeSM, pools, N_LEVELS,
    { quadCompleteFrom: 1 });

  // U7-4b: THE ROOT POOL'S SOLVER HALF, from amr2d-gpu.mjs -- the root step,
  // the criterion redirect, U5-3's live coupling and U2's mirror (a
  // comparator setup since U7-6f moved the seed to the host).
  // See makeRootPool for the solver/instrument split; the instrument and the
  // debugCheckRoot* comparators stay on index-amr.html.
  const rootGpu = makeRootPool(device, U, layouts, rootModules, pools,
    { W, H, RB, F16, DC_PRE, step1Constants, couplingConstants, cardStateBuf });
  // The root pool's initial field was seeded above, next to this page's own
  // initF() -- U7-6f moved it off the GPU mirror, which needed the dense
  // buffer to hold the IC. An unseeded root drives refinement off an unwritten
  // buffer, which is the state bug 1.2's fingerprint gate caught.


  const criterionPoolPLs = {};
  const managePoolDecidePLs = {};
  const managePoolCoarsenPLs = {};
  const managePoolRefinePLs = {};
  // U5-4: `m` is the PARENT level, and it starts at the ROOT once the root is
  // a pool level. One manager, every level.
  for (let m = 0; m < N_LEVELS - 1; m++) {
    const parentPool = pools[m];
    const childParams = paramsForChildLevel(m + 1);
    const poolConstants = {
      W, H, RB,
      NBX_PARENT: parentPool.NBX, NBY_PARENT: parentPool.NBY,
      PARENT_CELL_SIZE_L0: cellSizeL0AtLevel(m),
      ...childParams,
      HAS_BODY: 0,
      // U5-4 left DIAG implicit here on the grounds that "this page has no
      // ?diag= flag" -- it does, declared above, and its only consumer was
      // the DENSE manager's constants bundle. U7-6f deleted that bundle, so
      // the flag is passed through rather than the const deleted: `?diag=1`
      // now enables the refusal counter here the way it does on the card and
      // cylinder pages, and at DIAG=0 (the default) every counter stays 0.
      DIAG,
    };
    criterionPoolPLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [criterionPoolBGL] }),
      // GHOST 0 at the root, which selects the ring-free stencil. NBY_PARENT
      // is only read on that path.
      compute: { module: criterionPoolSM, entryPoint: 'main',
                 constants: m === 0
                   ? { RB, NBX_PARENT: parentPool.NBX, NBY_PARENT: parentPool.NBY, GHOST: 0 }
                   : { RB, NBX_PARENT: parentPool.NBX } }
    });
    managePoolDecidePLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [managePoolBGL] }),
      compute: { module: managePoolSM, entryPoint: 'decide', constants: poolConstants }
    });
    managePoolCoarsenPLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [managePoolBGL] }),
      compute: { module: managePoolSM, entryPoint: 'coarsen', constants: poolConstants }
    });
    managePoolRefinePLs[m] = device.createComputePipeline({
      layout: device.createPipelineLayout({ bindGroupLayouts: [managePoolBGL] }),
      compute: { module: managePoolSM, entryPoint: 'refine', constants: poolConstants }
    });
  }

  // Level 1's own fine-step bind groups, in the SAME layout every other level
  // uses -- the c>=2 loop below builds the identical pair. Level 1 differs
  // only in what its levelParams says (dxL 0.5, parentTau = L0's own tau);
  // there is no longer a second kernel, layout or pipeline for it.
  // plans/2D-backport.md B3-1.
  pools[1].step1BG_ab = device.createBindGroup({ layout: step1BGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: pools[1].finePoolF_a } }, { binding: 2, resource: { buffer: pools[1].finePoolF_b } }, { binding: 3, resource: { buffer: pools[1].finePoolVel } }, { binding: 4, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 5, resource: { buffer: pools[1].levelParamsBuf } }, { binding: 6, resource: { buffer: pools[1].blockSlotBuf } }]});
  pools[1].step1BG_ba = device.createBindGroup({ layout: step1BGL, entries: [{ binding: 0, resource: { buffer: cardStateBuf } }, { binding: 1, resource: { buffer: pools[1].finePoolF_b } }, { binding: 2, resource: { buffer: pools[1].finePoolF_a } }, { binding: 3, resource: { buffer: pools[1].finePoolVel } }, { binding: 4, resource: { buffer: pools[1].slotToBlockBuf } }, { binding: 5, resource: { buffer: pools[1].levelParamsBuf } }, { binding: 6, resource: { buffer: pools[1].blockSlotBuf } }]});

  const overlayOpacityBuf = device.createBuffer({ size: 4, usage: U.UNIFORM | U.COPY_DST });
  device.queue.writeBuffer(overlayOpacityBuf, 0, new Float32Array([1.0]));
  const outlineOpacityBuf = device.createBuffer({ size: 4, usage: U.UNIFORM | U.COPY_DST });
  device.queue.writeBuffer(outlineOpacityBuf, 0, new Float32Array([0.0]));
  if (overlaySlider) {
    overlaySlider.oninput = () => {
      const v = parseFloat(overlaySlider.value);
      overlayValEl.textContent = v.toFixed(2);
      device.queue.writeBuffer(overlayOpacityBuf, 0, new Float32Array([v]));
    };
  }
  // U6: one velocity/indirection pair per POOL level, walked finest-first by
  // shaders/amr_render.wgsl. Shared with the other four AMR pages, which all
  // built this inline and three of which never passed the level-2 override at
  // all -- see makeRenderBindGroup.
  const renBG = makeRenderBindGroup(device, renBGL, pools,
    { cardStateBuf, overlayOpacityBuf, outlineOpacityBuf });

  // U5-3: level 1's coupling to the ROOT, named ONCE -- see makeRootPool's
  // `coupleL1` for why selecting it per dispatch site is the trap.
  const {
    interpPL:     l1InterpPL,
    interpInitPL: l1InterpInitPL,
    interpFFPL:   l1InterpFFPL,
    interpBG:     l1InterpBG,
    interpInitBG: l1InterpInitBG,
    interpFFBG:   l1InterpFFBG,
  } = rootGpu.coupleL1();


  // U7-2: one criterion/manage bind-group pair per parent level, from ONE
  // place -- byte-identical across four pages before this, and differing on
  // the fifth only by where the loop starts. See makeManageBindGroups.
  const { criterionPoolBGs, managePoolBGs } = makeManageBindGroups(
    device, layouts, pools, N_LEVELS,
    { cardStateBuf, diagBuf });


  // U7-2: every level >= 2's interp / step / average / force bind groups, from
  // ONE place. Three pages had this loop byte-identical and two had it minus
  // the force block; see makeLevelBindGroups.
  makeLevelBindGroups(device, U, layouts, pools, N_LEVELS,
    { cardStateBuf });

  const error = await device.popErrorScope();
  if (error) { handleErr(error); return; }

  const WGX1 = Math.ceil(FB / 8), WGY1 = Math.ceil(FB / 8);
  const STEPS_PER_FRAME = 64;
  let step = 0, lastT = performance.now();
  let useB = false;
  let liveMode = true;
  // Default ON, unlike main-channel-amr.js -- see this file's own header:
  // TGV is fully periodic with no interior body, exactly the ALREADY-
  // VALIDATED coarse-fine interpolation path every other AMR page here
  // already exercises, so there's no known corruption risk the way
  // channel flow's real walls created for Couette.
  let autoRefine = urlParams.get('autoRefine') !== '0';
  let macroStepCounter = 0;

  // U7-3: WHAT each pass is. The ORDER is amr2d-gpu.mjs's makeScheduler, which
  // was byte-identical across four pages and differed on the fifth only by the
  // root pool -- see its header for why the seam is order vs. content.
  const passes = {
    l0InterpIntoL1: (enc, useB) => {
      const p = enc.beginComputePass();
      p.setPipeline(l1InterpPL);
      p.setBindGroup(0, l1InterpBG(useB));
      p.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); p.end();
    },
    // LEVEL 0's STEP. It ran alongside a dense L0 step from U3 until U7-6f;
    // the root pool is the only L0 now. See makeRootPool's encodeRootStep.
    l0Step: (enc, useB) => rootGpu.encodeRootStep(enc, useB),
    // Level 1's restriction into level 0. See makeRootPool's encodeRootAverage.
    l1AverageIntoL0: (enc, useB) => rootGpu.encodeRootAverage(enc, useB),
    interpIntoChild: (enc, level, readCur) => {
      const childPool = pools[level + 1];
      const bg = readCur === 'a' ? childPool.interpPoolParentBG_readA : childPool.interpPoolParentBG_readB;
      const p = enc.beginComputePass();
      p.setPipeline(interpPoolParentPL); p.setBindGroup(0, bg);
      p.dispatchWorkgroups(WGX1, WGY1, childPool.MAX_FINE_BLOCKS); p.end();
    },
    averageFromChild: (enc, level, writeCur) => {
      const childPool = pools[level + 1];
      const bg = writeCur === 'a' ? childPool.avgPoolBG_targetA : childPool.avgPoolBG_targetB;
      const p = enc.beginComputePass();
      p.setPipeline(avgPoolPL); p.setBindGroup(0, bg);
      p.dispatchWorkgroups(1, 1, childPool.MAX_FINE_BLOCKS); p.end();
    },
    // NO LEVEL SPLIT SINCE B3-1: one kernel, one pipeline, every level.
    substep: (enc, level, readCur) => {
      const pool = pools[level];
      const bg = readCur === 'a' ? pool.step1BG_ab : pool.step1BG_ba;
      const p = enc.beginComputePass();
      p.setPipeline(step1PL); p.setBindGroup(0, bg);
      p.dispatchWorkgroups(WGX1, WGY1, pool.MAX_FINE_BLOCKS); p.end();
    },
    fineFineRefresh: (enc, level) => {
      const pool = pools[level];
      const p = enc.beginComputePass();
      if (level === 1) { p.setPipeline(l1InterpFFPL); p.setBindGroup(0, l1InterpFFBG); p.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); }
      else { p.setPipeline(interpPoolParentFFPL); p.setBindGroup(0, pool.interpPoolParentFFBG_b); p.dispatchWorkgroups(WGX1, WGY1, pool.MAX_FINE_BLOCKS); }
      p.end();
    },
  };
  const { S_Advance: S_AdvanceShared } = makeScheduler({
    nLevels: N_LEVELS, ghostCopy: () => !!GHOST_COPY, passes,
  });
  const S_Advance = (level, enc) => S_AdvanceShared(level, enc, useB);

  function dispatchMacroStep(enc) {
    const interpInitBG = l1InterpInitBG(useB);

    // U7-3: WHAT each pass of the refinement round is. The ORDER -- and the
    // three separate places it is subtle -- is amr2d-gpu.mjs's
    // makeRefineRound, byte-identical across four pages before this.
    const refinePasses = {
      poolCriterion: (enc, m) => { const p = enc.beginComputePass(); p.setPipeline(criterionPoolPLs[m]); p.setBindGroup(0, criterionPoolBGs[m]); p.dispatchWorkgroups(2, 2, pools[m].MAX_FINE_BLOCKS); p.end(); },
      poolDecide: (enc, m) => { const p = enc.beginComputePass(); p.setPipeline(managePoolDecidePLs[m]); p.setBindGroup(0, managePoolBGs[m]); p.dispatchWorkgroups(Math.ceil(pools[m].MAX_FINE_BLOCKS / 64)); p.end(); },
      poolCoarsen: (enc, m) => { const p = enc.beginComputePass(); p.setPipeline(managePoolCoarsenPLs[m - 1]); p.setBindGroup(0, managePoolBGs[m - 1]); p.dispatchWorkgroups(Math.ceil(pools[m].MAX_FINE_BLOCKS / 64)); p.end(); },
      poolRefine: (enc, m) => { const p = enc.beginComputePass(); p.setPipeline(managePoolRefinePLs[m - 1]); p.setBindGroup(0, managePoolBGs[m - 1]); p.dispatchWorkgroups(Math.ceil(pools[m - 1].MAX_FINE_BLOCKS / 64)); p.end(); },
      l1InitFill: (enc) => { const p = enc.beginComputePass(); p.setPipeline(l1InterpInitPL); p.setBindGroup(0, interpInitBG); p.dispatchWorkgroups(WGX1, WGY1, MAX_FINE_BLOCKS); p.end(); },
      poolInitFill: (enc, m) => { const p = enc.beginComputePass(); p.setPipeline(interpPoolParentInitPL); p.setBindGroup(0, pools[m].interpPoolParentBG_readA); p.dispatchWorkgroups(WGX1, WGY1, pools[m].MAX_FINE_BLOCKS); p.end(); },
    };
    if (autoRefine && macroStepCounter % REFINE_EVERY === 0) {
      makeRefineRound({
        nLevels: N_LEVELS, pools, cascade, encodeCascade,
        passes: refinePasses,
      })(enc);
    }
    macroStepCounter++;

    S_Advance(0, enc);

    useB = !useB;
  }

  function resetSim() {
    const f0 = initF();
    writeF(pools[1].finePoolF_a, initFPool(), MAX_FINE_BLOCKS * NCELLS1);
    device.queue.writeBuffer(cardStateBuf, 0, initCardState());
    for (let c = 1; c < N_LEVELS; c++) {
      const pool = pools[c];
      writeF(pool.finePoolF_a, initFPool(pool.MAX_FINE_BLOCKS), pool.MAX_FINE_BLOCKS * NCELLS1);
    }
    // EVERY POOL'S ALLOCATOR STATE, from the one function allocLevelPool
    // itself uses. This replaces the hand-written writeBuffer lists that had
    // drifted from it -- see writePoolInitialState's header for the defects
    // that drift produced. The root pool is included: pools[0] is a level like
    // any other and its velocity is read by the first refinement round after
    // this reset.
    //
    // THE ROOT GETS (0, 0) WHILE ITS `f` CARRIES A TAYLOR-GREEN VORTEX, and
    // that is an approximation, not a value. Every other page whose IC is
    // uniform rest gets (0,0) EXACTLY right -- `feq(1,0,0,i)` represents zero
    // velocity -- and this page's does not. It lasts exactly one criterion
    // evaluation (the step recomputes velocity from `f` immediately after),
    // so the blast radius is which tiles exist at step 0.
    //
    // IT IS ALSO WHY "ZERO ACTIVE TILES" ON THIS PAGE IS NOT YET EVIDENCE
    // ABOUT THE THRESHOLDS. CLAUDE.md attributes that to thresholds which
    // never fire at TGV's vorticity scale; the first criterion round here
    // reads a ZERO field, so zero tiles at step 0 is guaranteed for an
    // unrelated reason. Seeding the true velocity would test the attribution.
    // See plans/uniform-levels.md, "U7-6f -- WHAT IT LEFT BEHIND".
    for (const pool of pools) {
      if (pool) writePoolInitialState(device, pool, { velFill: [0, 0] });
    }
    macroStepCounter = 0;
    useB = false;
    // U5-3: the root pool is L0 too, and reset() has to reach it. `useB =
    // false` above is the phase the seed writes (finePoolF_a).
    seedRootFrom(f0);
    step = 0;
  }

  // Pool indirection readback -- amr2d-gpu.mjs, five copies before B3a.
  const readPoolIndirection = (level = 1) => readPoolIndirectionOn(device, pools, level);
  async function setAutoRefine(v) { autoRefine = !!v; }

  // Active blocks of one level -- amr2d-gpu.mjs, five copies before B3a.
  const debugListActiveBlocks = (level = 1) => listActiveBlocks(device, pools, level);
  // 2:1 BALANCE. The rule, the multi-level readback and the corner-balance
  // decision all live in amr2d-gpu.mjs / amr2d.mjs now -- they were five
  // copies of one checker across the AMR pages, byte-identical in the
  // readback and already drifted in the checker. amr2d.mjs's pure half is
  // exercised by `make test` on inputs that VIOLATE the invariant, which an
  // in-page copy could never be.
  //
  // Cheap enough to call periodically during development and validation; not
  // wired into the live per-macro-step path, which would need a GPU-side
  // assertion mechanism this project does not have.
  const debugCheck21Balance = () => check21BalanceOnGPU(device, pools, N_LEVELS);
  // How far this topology is from the 2:1 closure -- amr2d-gpu.mjs.
  // Reports, does not gate: the shipped manager implements the rule as
  // per-pass tests and only the VETO half of the refine cascade exists,
  // so this is expected to be nonzero until plans/2D-backport.md B2.
  const debugCheckRefinementClosure = () => checkRefinementClosureOnGPU(device, pools, N_LEVELS);
  // A slot's quadrant is `slot % 4` by construction -- amr2d.mjs's
  // quadrantOfSlot. This scores the stored buffer against that rule over
  // live ACTIVE slots, which is what lets the pool manager stop writing it.
  const debugCheckSlotQuadrants = () => checkSlotQuadrantsOnGPU(device, pools, N_LEVELS);

  // THE GPU CASCADE, SCORED AGAINST THE HOST TWIN (plans/2D-backport.md B2-2).
  //
  // Nothing in the simulation consumes the want arrays yet -- this is the
  // closure built and proved correct BEFORE anything depends on it, the same
  // order B4-1 took before B4-2. `seeds` is a list of want sets in
  // amr2d.mjs's "bx,by" form; each is written to the GPU, closed by
  // shaders/amr_cascade.wgsl, and required to match cascade21's result
  // EXACTLY. Omit it and a default battery runs -- see makeCascadeSeeds.
  //
  // The seeds matter more than the driver: a closure only ever run on valid
  // input is indistinguishable from one that returns its input unchanged, so
  // the battery deliberately includes sets that VIOLATE 2:1 balance, sit on
  // the periodic seam, and want one child of a quad with no siblings.
  async function debugCascadeRoundTrip(seeds) {
    const battery = seeds || makeCascadeSeeds(pools, N_LEVELS);
    const results = [];
    for (const { name, sets } of battery) {
      const r = await cascadeRoundTrip(device, pools, N_LEVELS, cascade, sets);
      results.push({ name, ...r });
    }
    return { ok: results.every(r => r.ok), results };
  }


  // CONSERVATION, for plans/2D-backport.md B0b's interface instrument.
  // Amounts to one readback of the dense L0 grid; see readConservedTotals for
  // why that is the WHOLE hybrid system's total and not just the coarse
  // level's, and why TGV in particular is where the number means anything
  // (periodic, no body, no sponge, no walls -- so each level alone conserves
  // both exactly and any drift is the coarse/fine interface).
  //
  // THE CURRENT BUFFER IS READ FROM `useB`, NOT ASSUMED. debugSnapshotSave
  // can hardcode the _a buffer because STEPS_PER_FRAME is even and useB
  // therefore returns to false at every frame boundary -- but that is an
  // invariant of how it is called, and a diagnostic taking checkpoints at
  // arbitrary step counts should not inherit it.
  //
  // `readConservedTotals` is parameterised by a `cellIndex` callback precisely
  // so it can walk either representation of level 0 in spatial order
  // (amr2d.mjs's rootCellIndex header, U4-4). Handing it the root's mapping
  // and the root's `f` is the whole of the U7-6f change here.
  const rootSpec = rootPoolSpec({ dims: { W, H }, rb: RB });
  const debugConservedTotals = () => readConservedTotals(device, {
    f: useB ? pools[0].finePoolF_b : pools[0].finePoolF_a,
    W, H, NCELLS: rootSpec.cells, ex: EX, ey: EY,
    decode: readF, cellIndex: cellIndexJS,
  });

  // The rigid body's own state, keyed by common_geometry.wgsl's CardState --
  // amr2d-gpu.mjs, three byte-identical copies before B4.
  const debugReadCardState = () => readCardState(device, cardStateBuf);

  async function debugStepSync(n) {
    liveMode = false;
    for (let k = 0; k < n; k += STEPS_PER_FRAME) {
      const enc = device.createCommandEncoder();
      for (let s = 0; s < STEPS_PER_FRAME; s++) dispatchMacroStep(enc);
      device.queue.submit([enc.finish()]);
      await device.queue.onSubmittedWorkDone();
      step += STEPS_PER_FRAME;
    }
    return { step };
  }

  const stagingVel = device.createBuffer({ size: NCELLS * 2 * 4, usage: U.MAP_READ | U.COPY_DST });

  // Full 2D velocity field. Reads LEVEL 0's velocity directly -- its own step
  // kernel writes every cell every step regardless of refinement, and the
  // average pass (S_Advance) overwrites any refined block's level-0 cells with
  // the finer level's restricted value, so it always holds the
  // finest-available data even in a partially-refined domain (same reasoning
  // as main-channel-amr.js's readProfile). Tile-major indexing (cellIndexJS),
  // not flat row-major -- see rootCellIndex.
  async function readField() {
    const enc = device.createCommandEncoder();
    enc.copyBufferToBuffer(pools[0].finePoolVel, 0, stagingVel, 0, NCELLS * 2 * 4);
    device.queue.submit([enc.finish()]);
    await stagingVel.mapAsync(GPUMapMode.READ);
    const vel = new Float32Array(stagingVel.getMappedRange()).slice();
    stagingVel.unmap();
    const ux = new Array(NCELLS), uy = new Array(NCELLS);
    for (let y = 0; y < H; y++) {
      for (let x = 0; x < W; x++) {
        const cell = cellIndexJS(x, y);
        const flat = y * W + x;
        ux[flat] = vel[cell * 2];
        uy[flat] = vel[cell * 2 + 1];
      }
    }
    return { ux, uy };
  }

  function getLevelPoolSizes() {
    return pools.slice(1).map(p => ({
      level: p.level,
      NBX: p.NBX, NBY: p.NBY, NBLOCKS: p.NBLOCKS,
      MAX_FINE_BLOCKS: p.MAX_FINE_BLOCKS,
    }));
  }

  window.__CYL = {
    setLive: (v) => { liveMode = !!v; },
    isLive: () => liveMode,
    reset: resetSim,
    getStep: () => step,
    getDims: () => ({ W, H, N }),
    getParams: () => ({ N, W, H, TAU, U0, nu: nuFromTau(TAU), kx: KX, ky: KY, td: tdFromNu(nuFromTau(TAU)) }),
    readField,
    debugStepSync,
    debugReadCardState,
    debugCheck21Balance,
    debugCheckRefinementClosure,
    debugCheckSlotQuadrants,
    debugCascadeRoundTrip,
    debugConservedTotals,
    debugListActiveBlocks,
    setAutoRefine,
    isAutoRefine: () => autoRefine,
    getBlockGridDims: () => ({ NBX, NBY, RB, GHOST, FB, NCELLS1, MAX_FINE_BLOCKS }),
    getRefineParams: () => ({
      REFINE_EVERY, REFINE_THRESH, COARSEN_THRESH, FORCE_REFINE_MARGIN, FORCE_REFINE_LOOKAHEAD,
      perLevel: Array.from({ length: N_LEVELS - 1 }, (_, i) => ({ childLevel: i + 1, ...paramsForChildLevel(i + 1) })),
    }),
    getNumLevels: () => N_LEVELS,
    getRootPool: () => ({ ...rootGpu.spec, stepped: true }),
    getLevelPoolSizes,
    tauAtLevel,
  };

  async function frame() {
    try {
      if (!liveMode) {
        requestAnimationFrame(() => frame().catch(handleErr));
        return;
      }

      device.pushErrorScope('validation');
      const enc = device.createCommandEncoder();

      for (let s = 0; s < STEPS_PER_FRAME; s++) dispatchMacroStep(enc);
      step += STEPS_PER_FRAME;

      const rp = enc.beginRenderPass({ colorAttachments: [{ view: ctx.getCurrentTexture().createView(), clearValue: { r:0.07, g:0.07, b:0.1, a:1 }, loadOp: 'clear', storeOp: 'store' }]});
      rp.setPipeline(renPL); rp.setBindGroup(0, renBG); rp.draw(6); rp.end();

      device.queue.submit([enc.finish()]);
      device.popErrorScope().then(err => { if (err) handleErr(err); });

      if (performance.now() - lastT > 250) {
        statusEl.textContent = `[AMR] step ${step}  N=${N}  U0=${U0.toFixed(3)}  levels=${N_LEVELS}`;
        lastT = performance.now();
      }

      requestAnimationFrame(() => frame().catch(handleErr));
    } catch (e) {
      handleErr(e);
    }
  }
  frame().catch(handleErr);
}
init().catch(handleErr);
