// GENERATED by tools/gen-lattice-2d.js from lattice-2d.mjs. DO NOT EDIT.
// Regenerate with `node tools/gen-lattice-2d.js`; tools/test-lattice-2d.js
// fails on drift between the two, and independently checks the lattice moment
// conditions on the tables parsed back OUT of this file.
//
// Shared D2Q9 lattice basis, weights, bounce-back opposite-direction pairing,
// and the BGK equilibrium distribution -- identical across every kernel that
// streams/collides/interpolates on the D2Q9 lattice. Included via
// `// @include "common_lattice.wgsl"` (see shader-loader.mjs) rather than
// hand-copied.
//
// THE WEIGHTS ARE NOT THE PLAIN ROUNDED FRACTIONS. Each is moved by a whole
// number of f32 ulps so that they sum to EXACTLY 1; without that, every
// collision injects omega*rho*1.49e-8 of mass per cell per step, which
// compounds linearly for the length of a run. lattice-2d.mjs carries the
// derivation, the measurement and what the trade costs the moment conditions.
// The 17-digit literals are load-bearing: they are what make this file's f32
// and the host's the same number.

const ex = array<i32,9>( 0, 1, 0,-1, 0, 1,-1,-1, 1);
const ey = array<i32,9>( 0, 0, 1, 0,-1, 1, 1,-1,-1);
const wt = array<f32,9>(
  0.44444444775581360f,
  0.11111111193895340f,
  0.11111111193895340f,
  0.11111111193895340f,
  0.11111111193895340f,
  0.027777777984738350f,
  0.027777777984738350f,
  0.027777777984738350f,
  0.027777777984738350f
);
// Opposite-direction index for each of the 9 links. Structural rather than a
// table: each shell is enumerated counter-clockwise, so the opposite is the
// half-turn within the shell.
const opp = array<u32,9>(0u, 3u, 4u, 1u, 2u, 7u, 8u, 5u, 6u);
const CS2 = 0.33333334326744080f; // D2Q9 lattice speed of sound squared (1/3)

// Named feqD2Q9, not feq -- several including files (the fused step kernels)
// already have their own local `let feq = ...` inside their collision loop; a
// distinct name avoids relying on shadowing rules to keep the two apart.
fn feqD2Q9(rho: f32, ux: f32, uy: f32, i: u32) -> f32 {
  let eu = f32(ex[i]) * ux + f32(ey[i]) * uy;
  return wt[i] * rho * (1f + 3f*eu + 4.5f*eu*eu - 1.5f*(ux*ux+uy*uy));
}
